// tb_asu_rmsnorm.sv — ASU RMSNorm smoke (Verilator --binary --timing
// --assert). Expected values generated by gen_asu_vectors.py's rmsnorm_fx —
// the NORMATIVE golden mirror of asu_rmsnorm.sv's documented fixed-point
// contract (sum x^2 -> pow-2 mean shift -> +1 eps -> vendored rsqrt_unit
// floor(8192/isqrt) -> x*gamma*r with RNE>>18 to Q7.8, sat16).
//
// Proves:
//   T1: D=64 row bit-exact (INT8 extremes included), gamma streamed on its
//       own channel, dbg_norm (rsqrt floor-sqrt) checked against golden.
//       The D-018 wrapper only captures at rs_cnt == RSQRT_LATENCY &&
//       out_valid — a latency deviation would hang here and hit the
//       watchdog, and a mis-sample would break bit-exactness.
//   T2: D=3 (not a power of two) — legality reject: len_error pulse +
//       sticky, zero output beats, no done.
//   T3: 129-beat row (> RMS_D_MAX) — overflow reject through the FLUSH path.
//   T4: D=1 edge case (x = -128) bit-exact.
//   T5: T1 replay after both rejects — state clean.
//
// Output backpressure via LFSR; §5 stability checked by apex_stream1_sva on
// all three DUT stream boundaries; job-level D-006 assertions in the TB;
// $fatal watchdog.

`include "apex_stream1_sva.svh"

module tb_asu_rmsnorm;

  import apex_pkg::*;

  localparam int unsigned D_MAX = 128;

  `include "asu_vectors_rmsnorm.svh"

  // ── clock / reset / DUT ───────────────────────────────────────────────────
  logic clk;
  logic rst_n;
  initial begin
    clk = 1'b0;
    forever #5 clk = ~clk;
  end

  logic               s_valid, s_ready;
  logic signed [7:0]  s_x;
  logic               s_last;
  logic               g_valid, g_ready;
  logic signed [15:0] g_gamma;
  logic               m_valid, m_ready;
  logic signed [15:0] m_y;
  logic               m_last;
  logic               busy, done, len_error, len_error_sticky;
  logic        [13:0] dbg_norm;

  asu_rmsnorm #(
    .RMS_D_MAX (D_MAX)
  ) dut (
    .clk              (clk),
    .rst_n            (rst_n),
    .s_valid          (s_valid),
    .s_ready          (s_ready),
    .s_x              (s_x),
    .s_last           (s_last),
    .g_valid          (g_valid),
    .g_ready          (g_ready),
    .g_gamma          (g_gamma),
    .m_valid          (m_valid),
    .m_ready          (m_ready),
    .m_y              (m_y),
    .m_last           (m_last),
    .busy             (busy),
    .done             (done),
    .len_error        (len_error),
    .len_error_sticky (len_error_sticky),
    .dbg_norm         (dbg_norm),
    // R4 chunk composition: OFF (both levels 0) — this TB exercises
    // the frozen contract, which R4 leaves bit-identical when off
    .ext_sum_en       (1'b0),
    .ext_r_en         (1'b0),
    .ext_sum2         (28'd0),
    .ext_k            (7'd0),
    .s2_push          (s2_push),
    .s2_val           (s2_val)
  );

  // R4 OFF-mode guard: with both ext levels tied 0 the sum-capture export
  // must never fire — the frozen contract this TB grades is byte-identical
  logic        s2_push;
  logic [27:0] s2_val;
  always @(posedge clk) begin
    if (rst_n && (s2_push !== 1'b0 || s2_val !== 28'd0)) begin
      $display("FAIL: R4 export fired with ext levels off");
      $fatal(1);
    end
  end

  // ── §5 stream SVA (reused pack, bound onto all three boundaries) ─────────
  bind asu_rmsnorm apex_stream1_sva #(.WIDTH(9), .NAME("rms.x")) u_sva_x (
    .clk   (clk),
    .rst_n (rst_n),
    .valid (s_valid),
    .ready (s_ready),
    .data  ({s_x, s_last})
  );
  bind asu_rmsnorm apex_stream1_sva #(.WIDTH(16), .NAME("rms.g")) u_sva_g (
    .clk   (clk),
    .rst_n (rst_n),
    .valid (g_valid),
    .ready (g_ready),
    .data  (g_gamma)
  );
  bind asu_rmsnorm apex_stream1_sva #(.WIDTH(17), .NAME("rms.y")) u_sva_y (
    .clk   (clk),
    .rst_n (rst_n),
    .valid (m_valid),
    .ready (m_ready),
    .data  ({m_y, m_last})
  );

  // ── job-level D-006 / §3 assertions ───────────────────────────────────────
  ap_done_pulse_1cyc: assert property (@(posedge clk) disable iff (!rst_n)
    done |=> !done)
    else $error("[SVA D-006] done held more than one cycle");

  ap_done_means_idle: assert property (@(posedge clk) disable iff (!rst_n)
    done |-> !busy)
    else $error("[SVA §5] busy still high at done");

  ap_out_only_in_job: assert property (@(posedge clk) disable iff (!rst_n)
    m_valid |-> busy)
    else $error("[SVA D-019] output beat with no job in flight");

  ap_err_no_done: assert property (@(posedge clk) disable iff (!rst_n)
    len_error |-> !done)
    else $error("[SVA §3] done pulsed for a rejected row");

  ap_sticky_sets: assert property (@(posedge clk) disable iff (!rst_n)
    len_error |=> len_error_sticky)
    else $error("[SVA §3] sticky not set after len_error pulse");

  ap_sticky_holds: assert property (@(posedge clk) disable iff (!rst_n)
    len_error_sticky |=> len_error_sticky)
    else $error("[SVA §3] len_error_sticky cleared without reset");

  int errors;

  // ── watchdog ──────────────────────────────────────────────────────────────
  initial begin
    repeat (100000) @(posedge clk);
    $fatal(1, "WATCHDOG: simulation did not finish within 100000 cycles");
  end

  // ── monitors ──────────────────────────────────────────────────────────────
  int done_count;
  int err_pulses;
  always @(posedge clk) begin
    if (!rst_n) begin
      done_count <= 0;
      err_pulses <= 0;
    end else begin
      if (done)      done_count <= done_count + 1;
      if (len_error) err_pulses <= err_pulses + 1;
    end
  end

  logic [15:0] got_q [$];
  bit          got_last_q [$];
  logic [31:0] lfsr;
  always @(negedge clk) begin
    if (!rst_n) begin
      lfsr    <= 32'hACE1_2026;
      m_ready <= 1'b0;
    end else begin
      lfsr    <= {lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]};
      m_ready <= lfsr[0] | lfsr[3];      // ~75% duty
    end
  end
  always @(posedge clk) begin
    if (m_valid && m_ready) begin
      got_q.push_back(16'(m_y));
      got_last_q.push_back(m_last);
    end
  end

  int exp_beats_at_done;
  int d006_fails;
  always @(posedge clk) begin
    if (!rst_n) begin
      d006_fails <= 0;
    end else if (done && (got_q.size() != exp_beats_at_done)) begin
      d006_fails <= d006_fails + 1;
      $display("FAIL [D-006]: done with %0d/%0d beats accepted post-skid",
               got_q.size(), exp_beats_at_done);
    end
  end

  // ── stimulus ──────────────────────────────────────────────────────────────
  logic [7:0]  x_v   [D_MAX + 1];
  logic [15:0] g_v   [D_MAX];
  logic [15:0] exp_v [D_MAX];

  task automatic send_x(input logic [7:0] w, input bit last);
    @(negedge clk);
    s_x     = signed'(w);
    s_last  = last;
    s_valid = 1'b1;
    while (!s_ready) @(negedge clk);
    @(negedge clk);
    s_valid = 1'b0;
  endtask

  task automatic send_gamma(input logic [15:0] w);
    @(negedge clk);
    g_gamma = signed'(w);
    g_valid = 1'b1;
    while (!g_ready) @(negedge clk);
    @(negedge clk);
    g_valid = 1'b0;
  endtask

  task automatic drive_job(input int n);
    fork
      begin
        for (int i = 0; i < n; i++) send_x(x_v[i], i == n - 1);
      end
      begin
        for (int i = 0; i < n; i++) send_gamma(g_v[i]);
      end
    join
  endtask

  task automatic wait_done(input int target);
    while (done_count < target) @(negedge clk);
  endtask

  task automatic check_row(input string name, input int n,
                           input logic [13:0] exp_nrm);
    if (got_q.size() != n) begin
      errors++;
      $display("FAIL [%s]: expected %0d beats, got %0d", name, n, got_q.size());
    end else begin
      for (int i = 0; i < n; i++) begin
        if (got_q[i] !== exp_v[i]) begin
          errors++;
          $display("FAIL [%s]: y[%0d] got 0x%04x exp 0x%04x",
                   name, i, got_q[i], exp_v[i]);
        end
        if (got_last_q[i] !== bit'(i == n - 1)) begin
          errors++;
          $display("FAIL [%s]: beat %0d last=%0b (exp %0b)",
                   name, i, got_last_q[i], i == n - 1);
        end
      end
    end
    if (dbg_norm !== exp_nrm) begin
      errors++;
      $display("FAIL [%s]: dbg_norm=%0d exp %0d (rsqrt floor-sqrt)",
               name, dbg_norm, exp_nrm);
    end
    got_q.delete();
    got_last_q.delete();
  endtask

  // ── test sequence ─────────────────────────────────────────────────────────
  initial begin
    rst_n             = 1'b0;
    errors            = 0;
    exp_beats_at_done = 0;
    s_valid           = 1'b0;
    s_x               = '0;
    s_last            = 1'b0;
    g_valid           = 1'b0;
    g_gamma           = '0;

    repeat (5) @(negedge clk);
    rst_n = 1'b1;
    repeat (2) @(negedge clk);

    if (busy) begin
      errors++; $display("FAIL [reset]: busy asserted out of reset");
    end
    if (len_error_sticky) begin
      errors++; $display("FAIL [reset]: sticky error out of reset");
    end

    // ─── T1: D=64 bit-exact (x extremes, signed gammas, dbg_norm) ─────────
    $display("T1: D=%0d row (r=%0d nrm=%0d expected)", RMS_D0, RMS_R0, RMS_NRM0);
    for (int i = 0; i < RMS_D0; i++) begin
      x_v[i]   = RMS_X0[i];
      g_v[i]   = RMS_G0[i];
      exp_v[i] = RMS_EXP0[i];
    end
    exp_beats_at_done = RMS_D0;
    drive_job(RMS_D0);
    wait_done(1);
    check_row("T1", RMS_D0, RMS_NRM0);
    repeat (3) @(negedge clk);
    if (busy) begin
      errors++; $display("FAIL [T1]: busy stuck after done");
    end

    // ─── T2: D=3 (not a power of two) — reject at last beat ───────────────
    $display("T2: D=3 (non-pow-2) -> reject");
    x_v[0] = 8'd10; x_v[1] = 8'd20; x_v[2] = 8'd30;
    for (int i = 0; i < 3; i++) send_x(x_v[i], i == 2);
    repeat (5) @(negedge clk);
    if (err_pulses != 1) begin
      errors++; $display("FAIL [T2]: err_pulses=%0d (exp 1)", err_pulses);
    end
    if (!len_error_sticky) begin
      errors++; $display("FAIL [T2]: sticky bit not set");
    end
    if (got_q.size() != 0 || done_count != 1) begin
      errors++; $display("FAIL [T2]: side effects from rejected row");
    end
    if (busy) begin
      errors++; $display("FAIL [T2]: busy stuck after reject");
    end

    // ─── T3: 129 beats (> RMS_D_MAX) — overflow reject via FLUSH ──────────
    $display("T3: %0d-beat row -> overflow reject", D_MAX + 1);
    for (int i = 0; i < D_MAX + 1; i++) begin
      x_v[i] = 8'(i);
    end
    for (int i = 0; i < D_MAX + 1; i++) send_x(x_v[i], i == D_MAX);
    repeat (5) @(negedge clk);
    if (err_pulses != 2) begin
      errors++; $display("FAIL [T3]: err_pulses=%0d (exp 2)", err_pulses);
    end
    if (got_q.size() != 0 || done_count != 1) begin
      errors++; $display("FAIL [T3]: side effects from rejected row");
    end
    if (busy) begin
      errors++; $display("FAIL [T3]: busy stuck after reject");
    end

    // ─── T4: D=1 edge case ─────────────────────────────────────────────────
    $display("T4: D=1 (x=-128, gamma=1.5, r=%0d nrm=%0d expected)",
             RMS_R1, RMS_NRM1);
    x_v[0]   = RMS_X1[0];
    g_v[0]   = RMS_G1[0];
    exp_v[0] = RMS_EXP1[0];
    exp_beats_at_done = RMS_D1;
    drive_job(RMS_D1);
    wait_done(2);
    check_row("T4", RMS_D1, RMS_NRM1);

    // ─── T5: T1 replay after both rejects — state clean ────────────────────
    $display("T5: D=%0d replay after rejects", RMS_D0);
    for (int i = 0; i < RMS_D0; i++) begin
      x_v[i]   = RMS_X0[i];
      g_v[i]   = RMS_G0[i];
      exp_v[i] = RMS_EXP0[i];
    end
    exp_beats_at_done = RMS_D0;
    drive_job(RMS_D0);
    wait_done(3);
    check_row("T5", RMS_D0, RMS_NRM0);
    if (err_pulses != 2) begin
      errors++; $display("FAIL [T5]: stray len_error");
    end

    // ─── verdict ───────────────────────────────────────────────────────────
    repeat (5) @(negedge clk);
    errors += d006_fails;
    if (errors == 0) begin
      $display("ASU RMSNORM SMOKE: ALL TESTS PASSED");
      $display("  T1 D=64 bit-exact vs rmsnorm_fx (incl. dbg_norm)");
      $display("  T2 non-pow-2 D rejected: pulse+sticky, zero side effects");
      $display("  T3 oversize D rejected via FLUSH path");
      $display("  T4 D=1 edge bit-exact");
      $display("  T5 replay after rejects bit-exact (state clean)");
      $finish;
    end else begin
      $fatal(1, "ASU RMSNORM SMOKE: %0d FAILURE(S)", errors);
    end
  end

endmodule
