// tb_asu_softmax.sv — ASU online-softmax smoke (Verilator --binary --timing
// --assert). All expected values generated by gen_asu_vectors.py from the
// golden arbiter apex_golden.compute.online_softmax_fx (SCORE_FRAC = 0).
//
// Proves:
//   T1: 24-score row bit-exact — clustered scores with two ascending maxima
//       (l-rescale exercised twice), a duplicated final max (equal-to-max
//       path) and one clamped element (>=16 below max -> p = 0).
//   T2: single-element row -> p = 0x8000 (exactly 1.0, the UQ1.15 top).
//   T3: INT32-extreme row {-2^31, -2^31, 2^31-1, 2^31-1} — full 33-bit diff
//       arithmetic + rescale-through-clamp (l collapses to the new max).
//   T4: oversize row (SM_ROW_MAX+1 = 1025 beats) — legality reject:
//       row_error pulse + sticky, ZERO output beats, NO done, busy falls.
//   T5: T1's row again after the reject — state is clean.
//
// The output consumer applies pseudo-random backpressure (LFSR, ~75% duty)
// so both skids and the post-skid D-006 done gating are genuinely exercised.
// §5 stream stability is checked by apex_stream1_sva bound onto both DUT
// stream boundaries; job-level D-006 properties are asserted in this TB.
// TB discipline: stimulus at negedge, commits observed at posedge (house
// style, verif/mxe). $fatal watchdog bounds the run.

`include "apex_stream1_sva.svh"

module tb_asu_softmax;

  import apex_pkg::*;

  localparam int unsigned ROW_MAX = 1024;

  // golden vectors (generated into build/ by gen_asu_vectors.py)
  `include "asu_vectors_softmax.svh"

  // ── clock / reset / DUT ───────────────────────────────────────────────────
  logic clk;
  logic rst_n;
  initial begin
    clk = 1'b0;
    forever #5 clk = ~clk;
  end

  logic               s_valid, s_ready;
  logic signed [31:0] s_score;
  logic               s_last;
  logic               m_valid, m_ready;
  logic        [15:0] m_prob;
  logic               m_last;
  logic               busy, done, row_error, row_error_sticky;

  asu_softmax #(
    .SM_ROW_MAX (ROW_MAX),
    .SCORE_FRAC (0)
  ) dut (
    .clk              (clk),
    .rst_n            (rst_n),
    .s_valid          (s_valid),
    .s_ready          (s_ready),
    .s_score          (s_score),
    .s_last           (s_last),
    .m_valid          (m_valid),
    .m_ready          (m_ready),
    .m_prob           (m_prob),
    .m_last           (m_last),
    .busy             (busy),
    .done             (done),
    .row_error        (row_error),
    .row_error_sticky (row_error_sticky)
  );

  // ── §5 stream SVA (reused pack, bound onto the DUT boundaries) ────────────
  bind asu_softmax apex_stream1_sva #(.WIDTH(33), .NAME("softmax.s")) u_sva_s (
    .clk   (clk),
    .rst_n (rst_n),
    .valid (s_valid),
    .ready (s_ready),
    .data  ({s_score, s_last})
  );
  bind asu_softmax apex_stream1_sva #(.WIDTH(17), .NAME("softmax.m")) u_sva_m (
    .clk   (clk),
    .rst_n (rst_n),
    .valid (m_valid),
    .ready (m_ready),
    .data  ({m_prob, m_last})
  );

  // ── job-level D-006 / §3 assertions ───────────────────────────────────────
  ap_done_pulse_1cyc: assert property (@(posedge clk) disable iff (!rst_n)
    done |=> !done)
    else $error("[SVA D-006] done held more than one cycle");

  ap_done_means_idle: assert property (@(posedge clk) disable iff (!rst_n)
    done |-> !busy)
    else $error("[SVA §5] busy still high at done (beats pending after done?)");

  ap_out_only_in_job: assert property (@(posedge clk) disable iff (!rst_n)
    m_valid |-> busy)
    else $error("[SVA D-019] output beat with no job in flight (stale beat)");

  ap_err_no_done: assert property (@(posedge clk) disable iff (!rst_n)
    row_error |-> !done)
    else $error("[SVA §3] done pulsed for a rejected row");

  ap_sticky_sets: assert property (@(posedge clk) disable iff (!rst_n)
    row_error |=> row_error_sticky)
    else $error("[SVA §3] sticky not set after row_error pulse");

  ap_sticky_holds: assert property (@(posedge clk) disable iff (!rst_n)
    row_error_sticky |=> row_error_sticky)
    else $error("[SVA §3] row_error_sticky cleared without reset");

  int errors;

  // ── watchdog ──────────────────────────────────────────────────────────────
  initial begin
    repeat (100000) @(posedge clk);
    $fatal(1, "WATCHDOG: simulation did not finish within 100000 cycles");
  end

  // ── monitors ──────────────────────────────────────────────────────────────
  int done_count;
  int err_pulses;
  always @(posedge clk) begin
    if (!rst_n) begin
      done_count <= 0;
      err_pulses <= 0;
    end else begin
      if (done)      done_count <= done_count + 1;
      if (row_error) err_pulses <= err_pulses + 1;
    end
  end

  // output consumer with pseudo-random backpressure
  logic [15:0] got_q [$];
  bit          got_last_q [$];
  logic [31:0] lfsr;
  always @(negedge clk) begin
    if (!rst_n) begin
      lfsr    <= 32'hACE1_2026;
      m_ready <= 1'b0;
    end else begin
      lfsr    <= {lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]};
      m_ready <= lfsr[0] | lfsr[3];      // ~75% duty
    end
  end
  always @(posedge clk) begin
    if (m_valid && m_ready) begin
      got_q.push_back(m_prob);
      got_last_q.push_back(m_last);
    end
  end

  // D-006 spot check: at done, every beat already accepted post-skid
  int exp_beats_at_done;
  int d006_fails;
  always @(posedge clk) begin
    if (!rst_n) begin
      d006_fails <= 0;
    end else if (done && (got_q.size() != exp_beats_at_done)) begin
      d006_fails <= d006_fails + 1;
      $display("FAIL [D-006]: done with %0d/%0d beats accepted post-skid",
               got_q.size(), exp_beats_at_done);
    end
  end

  // ── stimulus (negedge-driven, house style) ────────────────────────────────
  logic [31:0] in_v  [ROW_MAX + 1];
  logic [15:0] exp_v [ROW_MAX];

  task automatic send_score(input logic [31:0] w, input bit last);
    @(negedge clk);
    s_score = signed'(w);
    s_last  = last;
    s_valid = 1'b1;
    while (!s_ready) @(negedge clk);
    @(negedge clk);                      // cross the committing posedge
    s_valid = 1'b0;
  endtask

  task automatic drive_row(input int n);
    for (int i = 0; i < n; i++) send_score(in_v[i], i == n - 1);
  endtask

  task automatic wait_done(input int target);
    while (done_count < target) @(negedge clk);
  endtask

  task automatic check_row(input string name, input int n);
    if (got_q.size() != n) begin
      errors++;
      $display("FAIL [%s]: expected %0d beats, got %0d", name, n, got_q.size());
    end else begin
      for (int i = 0; i < n; i++) begin
        if (got_q[i] !== exp_v[i]) begin
          errors++;
          $display("FAIL [%s]: p[%0d] got 0x%04x exp 0x%04x",
                   name, i, got_q[i], exp_v[i]);
        end
        if (got_last_q[i] !== bit'(i == n - 1)) begin
          errors++;
          $display("FAIL [%s]: beat %0d last=%0b (exp %0b)",
                   name, i, got_last_q[i], i == n - 1);
        end
      end
    end
    got_q.delete();
    got_last_q.delete();
  endtask

  // ── test sequence ─────────────────────────────────────────────────────────
  initial begin
    rst_n             = 1'b0;
    errors            = 0;
    exp_beats_at_done = 0;
    s_valid           = 1'b0;
    s_score           = '0;
    s_last            = 1'b0;

    repeat (5) @(negedge clk);
    rst_n = 1'b1;
    repeat (2) @(negedge clk);

    if (busy) begin
      errors++; $display("FAIL [reset]: busy asserted out of reset");
    end
    if (row_error_sticky) begin
      errors++; $display("FAIL [reset]: sticky error out of reset");
    end

    // ─── T1: 24-score row, bit-exact vs online_softmax_fx ─────────────────
    $display("T1: %0d-score row (2x rescale, dup max, 1 clamped)", SM_N0);
    for (int i = 0; i < SM_N0; i++) begin
      in_v[i]  = SM_IN0[i];
      exp_v[i] = SM_EXP0[i];
    end
    exp_beats_at_done = SM_N0;
    drive_row(SM_N0);
    repeat (2) @(negedge clk);
    if (!busy) begin
      errors++; $display("FAIL [T1]: busy low while row in flight");
    end
    wait_done(1);
    check_row("T1", SM_N0);
    repeat (3) @(negedge clk);
    if (busy) begin
      errors++; $display("FAIL [T1]: busy stuck after done");
    end

    // ─── T2: single-element row -> exactly 1.0 (0x8000) ───────────────────
    $display("T2: single-element row -> p = 0x8000");
    in_v[0]  = SM_IN1[0];
    exp_v[0] = SM_EXP1[0];
    exp_beats_at_done = SM_N1;
    drive_row(SM_N1);
    wait_done(2);
    check_row("T2", SM_N1);

    // ─── T3: INT32 extremes (33-bit diff + rescale-through-clamp) ─────────
    $display("T3: INT32-extreme row");
    for (int i = 0; i < SM_N2; i++) begin
      in_v[i]  = SM_IN2[i];
      exp_v[i] = SM_EXP2[i];
    end
    exp_beats_at_done = SM_N2;
    drive_row(SM_N2);
    wait_done(3);
    check_row("T3", SM_N2);
    if (err_pulses != 0 || row_error_sticky) begin
      errors++; $display("FAIL [T3]: unexpected row_error");
    end

    // ─── T4: oversize row (ROW_MAX+1) — legality reject, zero effects ─────
    $display("T4: oversize row (%0d beats) -> reject", ROW_MAX + 1);
    for (int i = 0; i < ROW_MAX + 1; i++) begin
      in_v[i] = 32'(i);
    end
    drive_row(ROW_MAX + 1);
    repeat (5) @(negedge clk);
    if (err_pulses != 1) begin
      errors++; $display("FAIL [T4]: err_pulses=%0d (exp 1)", err_pulses);
    end
    if (!row_error_sticky) begin
      errors++; $display("FAIL [T4]: sticky bit not set");
    end
    if (got_q.size() != 0) begin
      errors++; $display("FAIL [T4]: %0d output beats from rejected row",
                         got_q.size());
    end
    if (done_count != 3) begin
      errors++; $display("FAIL [T4]: done pulsed for rejected row");
    end
    for (int i = 0; i < 10; i++) begin
      @(negedge clk);
      if (busy && i == 9) begin
        errors++; $display("FAIL [T4]: busy stuck after reject");
      end
    end

    // ─── T5: T1 row again — state clean after the reject ──────────────────
    $display("T5: T1 row replay after reject");
    for (int i = 0; i < SM_N0; i++) begin
      in_v[i]  = SM_IN0[i];
      exp_v[i] = SM_EXP0[i];
    end
    exp_beats_at_done = SM_N0;
    drive_row(SM_N0);
    wait_done(4);
    check_row("T5", SM_N0);
    if (err_pulses != 1) begin
      errors++; $display("FAIL [T5]: stray row_error");
    end

    // ─── verdict ───────────────────────────────────────────────────────────
    repeat (5) @(negedge clk);
    errors += d006_fails;
    if (errors == 0) begin
      $display("ASU SOFTMAX SMOKE: ALL TESTS PASSED");
      $display("  T1 24-score row bit-exact vs online_softmax_fx");
      $display("  T2 single-element row -> 0x8000 (1.0)");
      $display("  T3 INT32-extreme row bit-exact (33-bit diff, clamp rescale)");
      $display("  T4 oversize row rejected: pulse+sticky, zero side effects");
      $display("  T5 replay after reject bit-exact (state clean)");
      $finish;
    end else begin
      $fatal(1, "ASU SOFTMAX SMOKE: %0d FAILURE(S)", errors);
    end
  end

endmodule
