#!/usr/bin/env python3
"""B1 stage-0: golden replica of the on-tile fp16 scale-composite arithmetic.

This is the ORACLE the walker's composite unit (B1_WALKER.md §1 item 2) is
checked against. It is a *replica*, not a new golden: every formula here is
transcribed from the spec emitter `gen_l3_vectors.py` (which is itself the
L3 choreography spec per docs/OPTIMIZATION.md:38), and the module's own
self-test re-derives every CS/QS word of all 27 L3 cases from the scale
values those same case files publish on their EFS/ESS expectation lines.
Golden is never edited; if this replica and the case stream disagree, the
replica is wrong.

The two composites (B1_WALKER.md §2):

  score composite `cs`   (gen_l3_vectors.py:375-381)
      comp64 = s_q * s_k[t] * (float(1 << SCORE_FRAC) / sqrt(D))
      comp32 = comp64.astype(np.float32)          <-- exactly ONE f32 narrowing
      emitted as the raw uint32 bit pattern of comp32.
      The single narrowing is load-bearing (S-3, D-021): folding in f64 and
      narrowing later changes the low mantissa bits and breaks ERO/ESS.

  P-requant composite `qs` (gen_l3_vectors.py:382-384)
      qs = f32_bits_exact(s_v[t] * 2**-15)        <-- the S-4 fold
      f32_bits_exact additionally ASSERTS the result is fp32-exact, fp16-grade
      (bits & 0x1FFF == 0) and positive-normal. Those assertions are part of
      the contract: the hardware composite may rely on them.

NOTE on where the inputs come from (corrected after adversarial review —
the first version of this note was wrong and drove a wrong design conclusion):
seam_feeder_quant *recomputes* s_k[t]/s_v[t] on record read
(rtl/seam/seam_feeder_quant.sv:12,160). It does NOT follow that the value is
unavailable earlier. At CQ-8 the recomputed scale is BIT-IDENTICAL to the
fp16 scale the KVQ already stored with the record (rtl/kvq/kvq_engine.sv:290),
because the row's max |code| is always exactly 127, so
RNE_f16(amax/127) == s_record. Verified over the suite tensors and 13k random
tokens: zero mismatches. A store-time scale cache therefore gives an on-tile
composite unit the value in time to emit in the host's exact order.
Grouped tiers (CQ-4/CQ-4+) recompute a *different* scale from the dequantized
record — store-time determined, but not the stored per-record scale.
extract_trace.py reports where each input first becomes observable on a TAP,
which is a strictly narrower question. Do not read that measurement as an
impossibility proof.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "golden"))

from apex_golden.attention import SCORE_FRAC          # noqa: E402
from apex_golden.fp import f16_bits_to_f64            # noqa: E402

# INDEPENDENCE PIN. Both this replica and gen_l3_vectors.py import SCORE_FRAC
# from the same module, and build/ is gitignored + regenerated by `make
# vectors`. Without a pin the self-test only proves the two COPIES agree: move
# the constant at source, regenerate, and it stays green at the wrong value
# (demonstrated — SCORE_FRAC=9 regenerates the whole corpus and still PASSes).
# The pin turns a silent shared-mode drift into a loud failure. If S-5 ever
# legitimately changes, update this line deliberately.
_SCORE_FRAC_PINNED = 10                 # S-5 = apex_pkg ASU_IN_FRAC (attention.py:75)
assert SCORE_FRAC == _SCORE_FRAC_PINNED, (
    f"S-5 drift: apex_golden.attention.SCORE_FRAC is {SCORE_FRAC}, this replica "
    f"is pinned to {_SCORE_FRAC_PINNED}. The composite arithmetic contract "
    f"changed — review B1_WALKER.md §2 before touching this pin.")
_OUT_FRAC_PINNED = 15                   # S-4 fold uses 2**-15 (attention.py:76)

__all__ = ["SCORE_FRAC", "score_composite", "p_requant_composite",
           "f32_bits_exact_checked"]

# The only composites whose input scale is not observable on any tap before it
# is needed: tip_auto_mixed's 4 profiling blocks x 8 folds, which use pass-1
# CQ-8 V scales that the pass-2 pv phase re-reads at a different tier. They ARE
# recoverable from the pass-1 stored record scales; they are excluded here only
# because this self-test is deliberately tap-scoped. Enumerated, not a fudge:
# a change in this number must be explained, not absorbed.
EXPECTED_SKIP = 32


def _f16(bits: int) -> float:
    """fp16 bit pattern -> exact python float."""
    return float(f16_bits_to_f64(np.array([int(bits)], dtype=np.uint16))[0])


def score_composite(s_q_bits: int, s_k_bits: int, D: int) -> int:
    """`cs` word: one f32 narrowing of s_q * s_k * 2^SCORE_FRAC / sqrt(D).

    Transcribed from gen_l3_vectors.py:375-381. Inputs are fp16 BIT PATTERNS
    (what the tile exposes on fs_*/ss_*); the return is the uint32 bit
    pattern of the single-narrowed f32, i.e. what `CS <word>` carries.
    """
    s_q = _f16(s_q_bits)
    s_k = _f16(s_k_bits)
    comp64 = np.float64(s_q) * np.float64(s_k) * \
        np.float64(float(1 << SCORE_FRAC) / math.sqrt(float(D)))
    comp32 = np.float64(comp64).astype(np.float32)
    return int(np.asarray(comp32).view(np.uint32))


def f32_bits_exact_checked(x: float, what: str) -> int:
    """Byte-for-byte transcription of gen_l3_vectors.py:133-140.

    Kept separate (and asserting) so the hardware contract's preconditions
    stay visible: the S-4 composite is always fp32-exact, fp16-grade and
    positive-normal. A composite unit MAY exploit these; a violation here
    means the assumption has been broken upstream.
    """
    b = np.float64(x).astype(np.float32)
    assert float(np.float64(b)) == float(x), f"{what}: not fp32-exact: {x}"
    bits = int(b.view(np.uint32))
    assert bits & 0x1FFF == 0, f"{what}: not fp16-grade: {bits:08x}"
    assert 0 < ((bits >> 23) & 0xFF) < 255 and bits >> 31 == 0, \
        f"{what}: not positive normal: {bits:08x}"
    return bits


def p_requant_composite(s_v_bits: int, what: str = "S-4 comp") -> int:
    """`qs` word (S-4 fold): f32_bits_exact(s_v * 2**-15).

    Transcribed from gen_l3_vectors.py:382-384. NOTE this is the *score-phase*
    QS only. The far more numerous QS words in store_kv/q-inject are
    `decompose_f16` per-element injection composites — data-path testbench
    scaffolding, NOT walker-owned. extract_trace.py separates the two.
    """
    return f32_bits_exact_checked(_f16(s_v_bits) * 2.0 ** -15, what)


# ── self-test: re-derive every composite of every L3 case ────────────────────

def selftest(build_dir: str) -> int:
    """Recompute every walker-owned CS/QS word in every case from the scales
    the case file itself publishes, and diff against the emitted words.

    This proves the replica is bit-exact against the live spec stream without
    reading (or touching) the golden model.
    """
    from extract_trace import extract_case, load_manifest  # local import

    b = Path(build_dir)
    man = load_manifest(b)
    if not man:
        print(f"selftest: no manifest under {b}; run gen_l3_vectors.py first")
        return 2

    n_cs = n_qs = tot_cs = tot_qs = 0
    bad, skipped = [], []
    seen_cs, seen_qs = set(), set()
    for c in man:
        tr = extract_case(b / "cases" / f"{c['name']}.txt", params=c)
        D = tr["params"]["D"]
        tot_cs += len(tr["channels"]["CS"])
        tot_qs += sum(1 for e in tr["channels"]["QS"] if e["role"] == "s4_fold")

        for e in tr["channels"]["CS"]:
            p = e["provenance"]
            if p.get("s_q_bits") is None or p.get("s_k_bits") is None:
                skipped.append((c["name"], "CS", e["t"], e["phase"]))
                continue
            got = score_composite(p["s_q_bits"], p["s_k_bits"], D)
            seen_cs.add((p["s_q_bits"], p["s_k_bits"], D))
            n_cs += 1
            if got != e["bits"]:
                bad.append((c["name"], "CS", e["t"],
                            f"replica {got:08x} != emitted {e['bits']:08x}"))

        for e in tr["channels"]["QS"]:
            if e["role"] != "s4_fold":
                continue
            p = e["provenance"]
            if p.get("s_v_bits") is None:
                skipped.append((c["name"], "QS", e["t"], e["phase"]))
                continue
            got = p_requant_composite(p["s_v_bits"])
            seen_qs.add(p["s_v_bits"])
            n_qs += 1
            if got != e["bits"]:
                bad.append((c["name"], "QS", e["t"],
                            f"replica {got:08x} != emitted {e['bits']:08x}"))

    print(f"cases                    : {len(man)}")
    print(f"CS words re-derived      : {n_cs} / {tot_cs}")
    print(f"QS(S-4) words re-derived : {n_qs} / {tot_qs}")
    print(f"distinct (s_q,s_k,D) triples : {len(seen_cs)}   "
          f"distinct s_v patterns : {len(seen_qs)}")
    print(f"skipped (no tap-observable input): {len(skipped)}")
    for row in skipped[:4]:
        print("   skip", row)

    # ── COVERAGE GATE ───────────────────────────────────────────────────────
    # Without this, a broken provenance resolver (or a drifted phase comment in
    # gen_l3_vectors.py) silently checks ZERO words and the oracle still says
    # PASS. Absence of mismatch is not evidence; coverage is.
    errs = []
    if n_cs != tot_cs:
        errs.append(f"CS coverage: re-derived {n_cs} of {tot_cs} — every CS "
                    f"word must resolve")
    if len(skipped) != EXPECTED_SKIP:
        errs.append(f"skipped {len(skipped)}, expected exactly {EXPECTED_SKIP} "
                    f"(the enumerated tip_auto profiling folds)")
    if n_qs != tot_qs - EXPECTED_SKIP:
        errs.append(f"QS coverage: re-derived {n_qs}, expected "
                    f"{tot_qs - EXPECTED_SKIP}")
    if not any(s[3] == "profile" for s in skipped) and skipped:
        errs.append("skipped words are not the expected tip_auto profile set")

    if bad:
        print(f"\nMISMATCHES: {len(bad)}")
        for row in bad[:40]:
            print("  ", row)
        print("\nCOMPOSITE REPLICA: FAIL")
        return 1
    if errs:
        print("\nCOVERAGE GATE FAILED:")
        for e in errs:
            print("  -", e)
        print("\nCOMPOSITE REPLICA: FAIL (coverage)")
        return 1
    print("\nCOMPOSITE REPLICA: PASS "
          f"({n_cs + n_qs} composite words bit-exact vs the L3 op stream; "
          f"{EXPECTED_SKIP} structurally tap-unresolvable folds excluded)")
    print("KNOWN COVERAGE LIMIT: the corpus does not discriminate f64-level "
          "reassociation of the cs product (an f64-associativity mutant "
          "survives). A directed tie-case vector is stage-3 work.")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    raise SystemExit(selftest(sys.argv[1] if len(sys.argv) > 1 else "build"))
