#!/usr/bin/env python3
"""gen_residual_vectors.py — bit-exact oracle for tb_residual_add.

residual_add computes the C-6 fp16 residual primitive  y = f16(a + b)  for two
fp16-grid operands.  The golden here is numpy's own fp16: both operand bit
patterns are decoded to float64 (exact), added (exact, since both are fp16-
grid), and narrowed to fp16 with round-half-to-even — identical to
apex_golden.transformer._f16(x) applied to a fp16-grid sum.

Emits build/res_{a,b,exp}.hex (4-hex fp16 patterns) + build/res_nvec.svh.

Sweep: a directed set that hits sign combinations, cancellation to zero, a RNE
tie at the fp16 rounding boundary, a subnormal, and an overflow-to-inf
saturation, PLUS a large random exponent-varied grid so the RNE narrower is
exercised across the whole fp16 range.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "golden"))
import numpy as np  # noqa: E402

from apex_golden.fp import f16_bits_to_f64, f64_to_f16_bits  # noqa: E402


def res_add(a_bits: np.ndarray, b_bits: np.ndarray) -> np.ndarray:
    """y = f16( f64(a) + f64(b) ), the C-6 residual primitive (RNE narrow)."""
    a = f16_bits_to_f64(a_bits)
    b = f16_bits_to_f64(b_bits)
    return f64_to_f16_bits(a + b)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="build")
    args = ap.parse_args()
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)

    a_l, b_l = [], []

    # ── directed corners ─────────────────────────────────────────────────────
    directed = [
        (0x0000, 0x0000),   # 0 + 0
        (0x3C00, 0x3C00),   # 1.0 + 1.0 = 2.0
        (0x4200, 0xC200),   # 3.0 + -3.0 = 0 (cancellation)
        (0x4500, 0xC200),   # 5.0 + -3.0 = 2.0
        (0x3C00, 0x0001),   # 1.0 + smallest subnormal -> 1.0 (round down)
        (0x3C01, 0x1400),   # RNE tie region near 1.0 + tiny
        (0x7BFF, 0x7BFF),   # 65504 + 65504 -> +inf (overflow saturation)
        (0xFBFF, 0xFBFF),   # -65504 + -65504 -> -inf
        (0x0001, 0x0001),   # subnormal + subnormal
        (0x3800, 0x3800),   # 0.5 + 0.5 = 1.0
        (0xC500, 0x4200),   # -5.0 + 3.0 = -2.0
        (0x7BFF, 0x3C00),   # near-max + 1.0 (RNE at the top normal)
    ]
    for a, b in directed:
        a_l.append(a); b_l.append(b)

    # ── random exponent-varied fp16 grid ─────────────────────────────────────
    rng = np.random.default_rng(0x5E5117A1)
    n_rand = 20000
    for _ in range(n_rand):
        ea = 2.0 ** rng.integers(-8, 9)
        eb = 2.0 ** rng.integers(-8, 9)
        av = rng.standard_normal() * ea
        bv = rng.standard_normal() * eb
        a_l.append(int(f64_to_f16_bits(np.array([av]))[0]))
        b_l.append(int(f64_to_f16_bits(np.array([bv]))[0]))

    a_arr = np.array(a_l, dtype=np.uint16)
    b_arr = np.array(b_l, dtype=np.uint16)
    e_arr = res_add(a_arr, b_arr)
    n = len(a_arr)

    def write_hex(name: str, vals) -> None:
        with open(out / name, "w") as f:
            f.write("".join(f"{int(v) & 0xFFFF:04x}\n" for v in vals))

    write_hex("res_a.hex", a_arr)
    write_hex("res_b.hex", b_arr)
    write_hex("res_exp.hex", e_arr)
    with open(out / "res_nvec.svh", "w") as f:
        f.write("// GENERATED by gen_residual_vectors.py — do not edit.\n")
        f.write(f"localparam int RES_NVEC = {n};\n")

    print(f"residual oracle: {n} fp16 add vectors "
          f"({len(directed)} directed + {n_rand} random) -> {out}")


if __name__ == "__main__":
    main()
