// tb_mxe_smoke.sv — MXE smoke testbench (Verilator --binary --timing --assert).
//
// Proves (per the MXE deliverable spec):
//   T1: one WS GEMM (M=4, K=8, N=8) with the C-2 requant epilogue, bit-exact
//       against golden vectors embedded below (generated by gen_vectors.py
//       from apex_golden.compute — gemm_i8 + requant_i32_to_i8, the arbiter).
//       The chosen scale/shift produce at least one exact RNE tie and INT8
//       saturation, so half-to-even and sat8 are both exercised.
//   T2: two illegal descriptors (K=2049 > K_MAX; OP_NOP with M=0) are each
//       consumed with a desc_error pulse + sticky bit and ZERO side effects
//       (no busy, no done, no result beats) — ARCHITECTURE.md §3.
//   T3: OS accumulate chain — the full M=4, K=16, N=8 problem split into two
//       OP_GEMM_OS descriptors (accumulate=0 then accumulate=1), raw INT32
//       drain checked after EACH descriptor. Proves accumulator residency /
//       retention (mxe_array OS semantics), job serialization behind done
//       (D-006), and that state is clean after the T2 rejects.
//   T4: ONE WS descriptor with K=13, N=5 — within-descriptor multi-pass
//       accumulation (KB=2), K-tail weight-row masking (klast=5) and N<8
//       column masking, checked bit-exact with GARBAGE driven on all padding
//       lanes so the DUT's masking (not benign vectors) is what's proven.
//
// The result consumer applies pseudo-random backpressure (LFSR) so the
// output skid and the post-skid done gating are genuinely exercised.
//
// TB discipline: all stimulus is driven and all handshake decisions are made
// at NEGEDGE (DUT state moves at posedge), removing sampling races; transfer
// commits are counted at posedge exactly as the DUT sees them.
// A $fatal watchdog bounds the run.

module tb_mxe_smoke;

  import apex_pkg::*;

  // ── golden vectors (embedded; provenance: gen_vectors.py, seed 20260707) ──
  // Test 1: scale=1 shift=6  (RNE tie present: True, saturated lanes: 14)
  localparam logic [63:0] T1_ACT [4] = '{
    64'h156b595fdd6c8dd5,
    64'hdbce668133d7f3f9,
    64'hc4554f7220bc4658,
    64'h4d96c27f4b8fa86a
  };
  localparam logic [63:0] T1_WGT [8] = '{
    64'h3a5a9904affd8919,
    64'hd7d2822290dd7153,
    64'h78ab1d21b8922f00,
    64'hb48f2db06ea9bd04,
    64'h8dcd606aa1039168,
    64'h4f2a425fd4daadf2,
    64'hbd9f27a3300aeec6,
    64'hd79727e60f2fd4c7
  };
  localparam logic [255:0] T1_EXP [4] = '{
    256'h0000000fffffff800000007f0000007fffffff80ffffff80ffffff800000007f,
    256'h0000007f0000007fffffff80ffffffef0000007fffffffedffffff80ffffff80,
    256'hffffff80ffffff800000007f0000007fffffffaa0000000100000065ffffff80,
    256'hffffffc0ffffff800000007f0000007f0000007f0000007f0000007f0000007f
  };
  localparam logic [15:0] T1_SCALE = 16'd1;
  localparam logic [4:0]  T1_SHIFT = 5'd6;
  localparam logic [63:0] T3_ACT_C0 [4] = '{
    64'h406971c2a80b1bad,
    64'he530df90f57e3f6d,
    64'h872febe40265761b,
    64'h7b13965d15ca331f
  };
  localparam logic [63:0] T3_ACT_C1 [4] = '{
    64'h70288cb6cb9b9181,
    64'h1c16d2735dce7f6f,
    64'h494afecbd14e6277,
    64'h9eafd3c6046dd201
  };
  localparam logic [63:0] T3_WGT_C0 [8] = '{
    64'hea9982739ac2d4ef,
    64'ha9ef2d109f6effd1,
    64'h0ce710b1d19228a6,
    64'h3bf9278f6131fc1d,
    64'h53ae460565a781e0,
    64'h4915693a60d5ad44,
    64'h405b8279efe511a6,
    64'haf6afea569daef4f
  };
  localparam logic [63:0] T3_WGT_C1 [8] = '{
    64'hc0caec2fa277e965,
    64'he4cbedbdf7aa7219,
    64'h98f9d84f71fccb13,
    64'hc6f0cec8187100cf,
    64'h76ad30a7912937c4,
    64'hfabb5706533c1a3f,
    64'hf23a0527b7c907f7,
    64'h35469b6967024d75
  };
  localparam logic [255:0] T3_EXP_C0 [4] = '{
    256'hffffeb400000040ffffff984ffffe73e00000f6600003fc500002878ffff9e0e,
    256'h00004abaffffb6ecffffc491ffff7fa300004430ffffc9f300001f3dffffa0bd,
    256'h00003630ffffe31effffa318ffff63300000014bffffda3f000045c8ffffc5ea,
    256'hffffd7870000826c000016df00000482ffffe2f7fffff101ffffa3110000459f
  };
  localparam logic [255:0] T3_EXP_C1 [4] = '{
    256'hffffab3f00001fb3ffff6f9200001e990000012000000434000015e0ffff3179,
    256'h000115d0ffffbacaffffebb1ffff25be000009b30000006d00004ddcffff94cc,
    256'h00008626ffffe2ebffffb5ccffff98eeffffff5cffff891a00005b35fffff624,
    256'hffff9c23000051dd000034c4000002ee00004401000019d3ffff97ee00009dcd
  };
  // Test 4: ONE WS descriptor, K=13 (2 passes, klast=5), N=5; pad lanes are
  // deliberate garbage (0xAA act / 0x55 wgt) that the DUT must mask out
  localparam logic [63:0] T4_ACT [8] = '{
    64'h9fbcc3aacb945d17,
    64'haaaaaa6286c59e4f,
    64'h9395b8432c93d539,
    64'haaaaaac3967d88fb,
    64'h05e8f1f747952f29,
    64'haaaaaa456afe2ca2,
    64'h2e3ac80ea953957e,
    64'haaaaaaf623c08d46
  };
  localparam logic [63:0] T4_WGT [10] = '{
    64'h1300f0bce0e3fe31,
    64'h554ea212015630b3,
    64'hfab28737c4682c22,
    64'h451bb9e903953870,
    64'h789f6126ace39b71,
    64'h5555553b32f1373b,
    64'h555555e40368902f,
    64'h5555557d24509ac3,
    64'h555555f1ea8ed63b,
    64'h555555229c476851
  };
  localparam logic [255:0] T4_EXP [4] = '{
    256'h000000000000000000000000ffffe8ff0000838e0000356affffd6b80000295c,
    256'h00000000000000000000000000001dca00000a720000488b0000087fffffb7b0,
    256'h000000000000000000000000ffffcc220000246a0000129bffffac69000026f0,
    256'h0000000000000000000000000000281a000059e00000485c00003ebe00001d54
  };

  // ── clock / reset / DUT ────────────────────────────────────────────────────
  logic clk;
  logic rst_n;
  initial begin
    clk = 1'b0;
    forever #5 clk = ~clk;
  end

  logic         desc_valid, desc_ready;
  mxe_desc_t    desc;
  logic         desc_error, desc_error_sticky, busy, done;
  logic         act_valid, act_ready;
  lane8_beat_t  act_beat;
  logic         wgt_valid, wgt_ready;
  lane8_beat_t  wgt_beat;
  logic         res_valid, res_ready;
  lane32_beat_t res_beat;

  mxe_top dut (
    .clk               (clk),
    .rst_n             (rst_n),
    .desc_valid        (desc_valid),
    .desc_ready        (desc_ready),
    .desc              (desc),
    .desc_error        (desc_error),
    .desc_error_sticky (desc_error_sticky),
    .busy              (busy),
    .done              (done),
    .act_valid         (act_valid),
    .act_ready         (act_ready),
    .act_beat          (act_beat),
    .wgt_valid         (wgt_valid),
    .wgt_ready         (wgt_ready),
    .wgt_beat          (wgt_beat),
    .res_valid         (res_valid),
    .res_ready         (res_ready),
    .res_beat          (res_beat)
  );

  int errors;

  // ── watchdog ───────────────────────────────────────────────────────────────
  initial begin
    repeat (100000) @(posedge clk);
    $fatal(1, "WATCHDOG: simulation did not finish within 100000 cycles");
  end

  // ── monitors (posedge — exactly what the DUT commits) ─────────────────────
  int done_count;
  int err_pulses;
  always @(posedge clk) begin
    if (!rst_n) begin
      done_count <= 0;
      err_pulses <= 0;
    end else begin
      if (done)       done_count <= done_count + 1;
      if (desc_error) err_pulses <= err_pulses + 1;
    end
  end

  // result consumer with pseudo-random backpressure
  logic [255:0] got_q [$];
  bit           got_last_q [$];
  logic [31:0]  lfsr;
  always @(negedge clk) begin
    if (!rst_n) begin
      lfsr      <= 32'hACE1_2026;
      res_ready <= 1'b0;
    end else begin
      lfsr      <= {lfsr[30:0], lfsr[31] ^ lfsr[21] ^ lfsr[1] ^ lfsr[0]};
      res_ready <= lfsr[0] | lfsr[3];    // ~75% duty backpressure
    end
  end
  always @(posedge clk) begin
    if (res_valid && res_ready) begin
      got_q.push_back(res_beat.data);
      got_last_q.push_back(res_beat.last);
    end
  end

  // D-006 spot check: at the done pulse, every result beat of the job must
  // already be accepted downstream (post-skid)
  int exp_beats_at_done;
  int d006_fails;
  always @(posedge clk) begin
    if (!rst_n) begin
      d006_fails <= 0;
    end else if (done && (got_q.size() != exp_beats_at_done)) begin
      d006_fails <= d006_fails + 1;
      $display("FAIL [D-006]: done with %0d/%0d beats accepted post-skid",
               got_q.size(), exp_beats_at_done);
    end
  end

  // ── stimulus helpers (all negedge-driven) ─────────────────────────────────
  function automatic mxe_desc_t mk_desc(
    input logic [7:0]  op,
    input logic [11:0] m, k, n,
    input logic        accumulate,
    input logic        requant_en,
    input logic [15:0] scale,
    input logic [4:0]  shift
  );
    mxe_desc_t d;
    d            = '0;
    d.opcode     = op;
    d.m_dim      = m;
    d.k_dim      = k;
    d.n_dim      = n;
    d.mode_os    = (op == 8'(OP_GEMM_OS));
    d.accumulate = accumulate;
    d.requant_en = requant_en;
    d.rq_scale   = scale;
    d.rq_shift   = shift;
    return d;
  endfunction

  task automatic send_desc(input mxe_desc_t d);
    @(negedge clk);
    desc       = d;
    desc_valid = 1'b1;
    while (!desc_ready) @(negedge clk);
    @(negedge clk);                       // cross the committing posedge
    desc_valid = 1'b0;
  endtask

  task automatic send_act(input logic [63:0] w, input bit last);
    @(negedge clk);
    act_beat.data = w;
    act_beat.last = last;
    act_valid     = 1'b1;
    while (!act_ready) @(negedge clk);
    @(negedge clk);
    act_valid = 1'b0;
  endtask

  task automatic send_wgt(input logic [63:0] w, input bit last);
    @(negedge clk);
    wgt_beat.data = w;
    wgt_beat.last = last;
    wgt_valid     = 1'b1;
    while (!wgt_ready) @(negedge clk);
    @(negedge clk);
    wgt_valid = 1'b0;
  endtask

  task automatic drive_job(input logic [63:0] acts [4],
                           input logic [63:0] wgts [8]);
    fork
      begin
        for (int m = 0; m < 4; m++) send_act(acts[m], m == 3);
      end
      begin
        for (int c = 0; c < 8; c++) send_wgt(wgts[c], c == 7);
      end
    join
  endtask

  task automatic wait_done(input int target);
    while (done_count < target) @(negedge clk);
  endtask

  task automatic check_results(input string name,
                               input logic [255:0] exp [4]);
    if (got_q.size() != 4) begin
      errors++;
      $display("FAIL [%s]: expected 4 result beats, got %0d",
               name, got_q.size());
    end else begin
      for (int m = 0; m < 4; m++) begin
        if (got_q[m] !== exp[m]) begin
          errors++;
          $display("FAIL [%s]: beat %0d\n  got %064x\n  exp %064x",
                   name, m, got_q[m], exp[m]);
        end
        if (got_last_q[m] !== bit'(m == 3)) begin
          errors++;
          $display("FAIL [%s]: beat %0d last=%0b (exp %0b)",
                   name, m, got_last_q[m], m == 3);
        end
      end
    end
    got_q.delete();
    got_last_q.delete();
  endtask

  // ── test sequence ──────────────────────────────────────────────────────────
  initial begin
    rst_n             = 1'b0;
    errors            = 0;
    exp_beats_at_done = 0;
    desc_valid        = 1'b0;
    desc              = '0;
    act_valid         = 1'b0;
    act_beat          = '0;
    wgt_valid         = 1'b0;
    wgt_beat          = '0;

    repeat (5) @(negedge clk);
    rst_n = 1'b1;
    repeat (2) @(negedge clk);

    if (busy) begin
      errors++; $display("FAIL [reset]: busy asserted out of reset");
    end
    if (desc_error_sticky) begin
      errors++; $display("FAIL [reset]: sticky error out of reset");
    end

    // ─── T1: WS GEMM M=4 K=8 N=8, requant epilogue (C-2 RNE + sat8) ───────
    $display("T1: WS GEMM 4x8x8 + requant (scale=%0d shift=%0d)",
             T1_SCALE, T1_SHIFT);
    exp_beats_at_done = 4;
    send_desc(mk_desc(8'(OP_GEMM_WS), 12'd4, 12'd8, 12'd8, 1'b0, 1'b1,
                      T1_SCALE, T1_SHIFT));
    @(negedge clk);
    if (desc_ready) begin
      errors++; $display("FAIL [T1]: desc_ready high while job in flight");
    end
    if (!busy) begin
      errors++; $display("FAIL [T1]: busy low right after descriptor accept");
    end
    drive_job(T1_ACT, T1_WGT);
    wait_done(1);
    check_results("T1", T1_EXP);
    if (done_count != 1) begin
      errors++; $display("FAIL [T1]: done_count=%0d (exp 1)", done_count);
    end
    if (err_pulses != 0 || desc_error_sticky) begin
      errors++; $display("FAIL [T1]: unexpected desc_error");
    end
    repeat (3) @(negedge clk);
    if (busy) begin
      errors++; $display("FAIL [T1]: busy stuck after done");
    end

    // ─── T2: illegal descriptors — reject, pulse+sticky, ZERO side effects ─
    $display("T2: illegal descriptors (K=2049; OP_NOP with M=0)");
    send_desc(mk_desc(8'(OP_GEMM_WS), 12'd4, 12'd2049, 12'd8,
                      1'b0, 1'b0, 16'd1, 5'd0));
    repeat (3) @(negedge clk);
    if (err_pulses != 1) begin
      errors++; $display("FAIL [T2a]: err_pulses=%0d (exp 1)", err_pulses);
    end
    if (!desc_error_sticky) begin
      errors++; $display("FAIL [T2a]: sticky bit not set");
    end
    send_desc(mk_desc(8'(OP_NOP), 12'd0, 12'd8, 12'd8,
                      1'b0, 1'b0, 16'd1, 5'd0));
    repeat (3) @(negedge clk);
    if (err_pulses != 2) begin
      errors++; $display("FAIL [T2b]: err_pulses=%0d (exp 2)", err_pulses);
    end
    for (int i = 0; i < 30; i++) begin
      @(negedge clk);
      if (busy) begin
        errors++; $display("FAIL [T2]: busy after illegal descriptor"); break;
      end
    end
    if (done_count != 1) begin
      errors++; $display("FAIL [T2]: done pulsed for illegal descriptor");
    end
    if (got_q.size() != 0) begin
      errors++; $display("FAIL [T2]: result beats from illegal descriptor");
    end
    if (!desc_ready) begin
      errors++; $display("FAIL [T2]: desc_ready lost after rejects");
    end

    // ─── T3: OS accumulate chain (K=16 as two K=8 descriptors), raw drain ──
    $display("T3: OS chain — desc1 accumulate=0, desc2 accumulate=1");
    exp_beats_at_done = 4;
    send_desc(mk_desc(8'(OP_GEMM_OS), 12'd4, 12'd8, 12'd8,
                      1'b0, 1'b0, 16'd0, 5'd0));
    drive_job(T3_ACT_C0, T3_WGT_C0);
    wait_done(2);
    check_results("T3.desc1", T3_EXP_C0);

    send_desc(mk_desc(8'(OP_GEMM_OS), 12'd4, 12'd8, 12'd8,
                      1'b1, 1'b0, 16'd0, 5'd0));
    drive_job(T3_ACT_C1, T3_WGT_C1);
    wait_done(3);
    check_results("T3.desc2", T3_EXP_C1);
    if (err_pulses != 2) begin
      errors++; $display("FAIL [T3]: stray desc_error during OS chain");
    end

    // ─── T4: single-descriptor multi-pass WS — K=13 (KB=2), N=5, raw ──────
    $display("T4: WS 4x13x5 multi-pass (klast=5 tail + N<5 masking, raw)");
    exp_beats_at_done = 4;
    send_desc(mk_desc(8'(OP_GEMM_WS), 12'd4, 12'd13, 12'd5,
                      1'b0, 1'b0, 16'd0, 5'd0));
    fork
      begin
        for (int i = 0; i < 8; i++) send_act(T4_ACT[i], i == 7);
      end
      begin
        for (int i = 0; i < 10; i++) send_wgt(T4_WGT[i], i == 9);
      end
    join
    wait_done(4);
    check_results("T4", T4_EXP);
    if (err_pulses != 2) begin
      errors++; $display("FAIL [T4]: stray desc_error");
    end

    // ─── verdict ───────────────────────────────────────────────────────────
    repeat (5) @(negedge clk);
    errors += d006_fails;
    if (errors == 0) begin
      $display("MXE SMOKE: ALL TESTS PASSED");
      $display("  T1 WS 4x8x8 requant bit-exact (RNE tie + sat8 exercised)");
      $display("  T2 2 illegal descriptors rejected, zero side effects");
      $display("  T3 OS accumulate chain bit-exact after each descriptor");
      $display("  T4 WS 4x13x5 multi-pass bit-exact (tail+column masking)");
      $finish;
    end else begin
      $fatal(1, "MXE SMOKE: %0d FAILURE(S)", errors);
    end
  end

endmodule
