#!/usr/bin/env python
"""gen_kvq_vectors.py — python-golden expected vectors for the D-008 flush
regression (tb_kvq_flush.sv).

Runs apex_golden.cq_codec (the D-001 arbiter model) on the committed
d64_T70_G64__CQ4 key inputs (golden/vectors, generated by golden/gen_vectors.py):
T=70, D=64, G=64, CQ-4, no outliers -> one full group (64 tokens) + one PARTIAL
group (g=6), exactly what the RTL flush must produce. Emits key_scales /
key_payload / expected_k_hat hex plus the A2/D-026 record + scale-bank images
(key_records / scale_bank, via cq_codec.pack_key_records + sram_row_bits — the
golden packers are imported, never re-derived) in the committed-vector format.
The full group commits ssid 0; the flushed partial group consumes ssid 1.

SELF-CHECK (generator-validation discipline): the committed golden set covers
this exact config end to end — including the partial tail group — so this
regenerated output must be BIT-IDENTICAL to the committed files. Any mismatch is
a hard failure. The TB then reads the *generated* directory, making the flush
regression's oracle the Python golden model.
"""
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "golden"))
from apex_golden import cq_codec as cq  # noqa: E402

FROZEN = REPO / "golden/vectors/d64_T70_G64__CQ4"
T, D, G, BITS = 70, 64, 64, 4


def read_hex(path, dtype):
    return np.array([int(line, 16) for line in path.read_text().split()],
                    dtype=dtype)


def write_hex(path, arr, width):
    path.write_text("".join(f"{int(v):0{width}x}\n" for v in arr))


def main(outdir):
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)

    K = read_hex(FROZEN / "input_k.f16.hex", np.uint16).reshape(T, D)
    blob = cq.compress_keys(K, BITS, G, [])
    khat = cq.decompress_keys(blob).reshape(-1)

    assert blob.groups == [(0, 64), (64, 70)], blob.groups
    assert blob.scales.size == 2 * D and blob.payload.size == (64 * D + 6 * D) // 2

    # A2/D-026 record + scale-bank images straight from the golden packers
    # (single source of truth: cq_codec.sram_row_bits / pack_key_records)
    row_bits = cq.sram_row_bits(D, BITS, 0, keyed=True)
    krecs, bank, ssids = cq.pack_key_records(blob, row_bits)
    assert ssids == [0, 1], ssids   # full group ssid 0; flushed tail ssid 1

    write_hex(out / "key_scales.f16.hex", blob.scales, 4)
    write_hex(out / "key_payload.u8.hex", blob.payload, 2)
    write_hex(out / "expected_k_hat.f32.hex", khat, 8)
    write_hex(out / "key_records.u8.hex", krecs.reshape(-1), 2)
    write_hex(out / "scale_bank.f16.hex", bank.reshape(-1), 4)
    print(f"gen_kvq_vectors: T={T} D={D} G={G} CQ-{BITS} -> "
          f"{len(blob.groups)} groups (full 64 + partial 6), "
          f"{blob.scales.size} scales, {blob.payload.size} payload bytes, "
          f"{khat.size} khat words, {krecs.shape[0]}x{krecs.shape[1]}B records "
          f"(ssids {ssids}), {bank.shape[0]}x{bank.shape[1]} bank rows -> {out}")

    # self-check vs the frozen golden set (bit-exact, value-level)
    for name, got, dt in (("key_scales.f16.hex", blob.scales, np.uint16),
                          ("key_payload.u8.hex", blob.payload, np.uint8),
                          ("expected_k_hat.f32.hex", khat, np.uint32),
                          ("key_records.u8.hex", krecs.reshape(-1), np.uint8),
                          ("scale_bank.f16.hex", bank.reshape(-1), np.uint16)):
        ref = read_hex(FROZEN / name, dt)
        if got.shape != ref.shape or not np.array_equal(got.astype(dt), ref):
            bad = int(np.flatnonzero(got.astype(dt) != ref)[0])
            raise SystemExit(f"GEN SELF-CHECK FAILED: {name} differs from the "
                             f"frozen golden set at index {bad} "
                             f"(got {got[bad]:#x}, frozen {ref[bad]:#x})")
    print("GEN SELF-CHECK: python-golden output is bit-identical to the frozen "
          "d64_T70_G64__CQ4 set (incl. the partial g=6 tail group and the "
          "D-026 record/scale-bank images)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "build/gen_t70")
