#!/usr/bin/env python3
"""gen_rope_vectors.py — RoPE smoke oracle for tb_rope, from the golden arbiter.

Everything the TB compares against is produced HERE from
apex_golden.transformer (imported, never retyped), mirroring
verif/asu/silu/gen_silu_vectors.py:

  build/rope_*.hex      per-channel-pair vectors swept over head_dim in
                        {64,128} and position m in 0..127. Each record is one
                        HF half-split pair (i, i+half):
                          u_q   : Q0.14 phase code                (14b, 4 hex)
                          x_i   : fp16 bits of x[i]               (16b, 4 hex)
                          x_ih  : fp16 bits of x[i+half]          (16b, 4 hex)
                          exp_i : fp16 bits of rope_fx(...)[i]    (16b, 4 hex)
                          exp_ih: fp16 bits of rope_fx(...)[i+half]
                        rope_fx is the golden C-ROPE mirror (LUT cos/sin +
                        exact float64 product + ONE fp16 RNE). Bit-exact (===).
  build/rope_nvec.svh   localparam int ROPE_NVEC = <count>;  (TB array sizing)
  build/rope_lut_*.hex  cos/sin base+slope ROMs for the Icarus $readmemh path
                        (SAME golden _cos_sin_lut_tables values as the canonical
                        rtl/rope/rope_lut_tables.svh localparam arrays).

Run:
    python3 \
        gen_rope_vectors.py --outdir build
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "golden"))
import numpy as np  # noqa: E402

from apex_golden.fp import f16_bits_to_f64, f64_to_f16_bits  # noqa: E402
from apex_golden.transformer import (  # noqa: E402
    CS_OUT_FRAC, PH_FRAC, _cos_sin_lut_tables, cos_fx, rope_fx,
    rope_phase_q, rope_theta, sin_fx,
)

HEAD_DIMS = (64, 128)
POSITIONS = range(0, 128)          # m = 0..127 (cache rows + decode token)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="build")
    args = ap.parse_args()
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)

    # ── C-ROPE LUT invariants (provenance-explicit; the RTL depends on them) ──
    assert int(cos_fx(np.array([0]))[0]) == (1 << CS_OUT_FRAC), "cos_fx(0)!=1.0"
    assert int(sin_fx(np.array([0]))[0]) == 0, "sin_fx(0)!=0"
    assert int(cos_fx(np.array([1 << (PH_FRAC - 2)]))[0]) == 0, "cos(1/4turn)!=0"
    assert int(sin_fx(np.array([1 << (PH_FRAC - 2)]))[0]) == (1 << CS_OUT_FRAC), \
        "sin(1/4turn)!=1.0"

    rng = np.random.default_rng(0xC0FFEE)
    u_q_l, x_i_l, x_ih_l, e_i_l, e_ih_l = [], [], [], [], []

    for hd in HEAD_DIMS:
        theta = rope_theta(hd)
        half = hd // 2
        for m in POSITIONS:
            # fp16-grid row with varied exponents to exercise the fp16 datapath
            base = rng.standard_normal(hd)
            escale = 2.0 ** rng.integers(-6, 7, size=hd).astype(np.float64)
            x = f16_bits_to_f64(f64_to_f16_bits(base * escale))   # snap to fp16
            y = rope_fx(x, m, theta)                              # fp16-grid f64
            u_q = rope_phase_q(m, theta)                          # [half]
            xb = f64_to_f16_bits(x)
            yb = f64_to_f16_bits(y)
            for i in range(half):
                u_q_l.append(int(u_q[i]) % (1 << PH_FRAC))
                x_i_l.append(int(xb[i]))
                x_ih_l.append(int(xb[i + half]))
                e_i_l.append(int(yb[i]))
                e_ih_l.append(int(yb[i + half]))

    n = len(u_q_l)

    def write_hex(name: str, vals, mask: int, width_hex: int) -> None:
        with open(out / name, "w") as f:
            f.write("".join(f"{int(v) & mask:0{width_hex}x}\n" for v in vals))

    write_hex("rope_u_q.hex",    u_q_l, 0x3FFF, 4)
    write_hex("rope_x_i.hex",    x_i_l, 0xFFFF, 4)
    write_hex("rope_x_ih.hex",   x_ih_l, 0xFFFF, 4)
    write_hex("rope_exp_i.hex",  e_i_l, 0xFFFF, 4)
    write_hex("rope_exp_ih.hex", e_ih_l, 0xFFFF, 4)

    with open(out / "rope_nvec.svh", "w") as f:
        f.write("// GENERATED by gen_rope_vectors.py — do not edit.\n")
        f.write(f"localparam int ROPE_NVEC = {n};\n")

    # ── cos/sin ROMs for the Icarus $readmemh path — SAME golden tables ──────
    cb, cs, sb, ss = _cos_sin_lut_tables()
    assert all(len(t) == 256 for t in (cb, cs, sb, ss))
    write_hex("rope_cos_base.hex",  cb, 0xFFFF, 4)
    write_hex("rope_cos_slope.hex", cs, 0x07FF, 3)
    write_hex("rope_sin_base.hex",  sb, 0xFFFF, 4)
    write_hex("rope_sin_slope.hex", ss, 0x07FF, 3)

    print(f"rope oracle: {n} channel-pair vectors "
          f"(head_dim in {list(HEAD_DIMS)}, m in 0..{max(POSITIONS)}) -> {out}")
    print(f"rope ROM   : 256 cos/sin base+slope -> {out} (Icarus $readmemh path)")


if __name__ == "__main__":
    main()
