# =============================================================================
# sim/filelist.f
# Verilator command-line source filelist for the tensor_core_tile non-UVM
# verification package. GENERATED by Verification Integration Node.
#
# Order below is TRANSCRIBED VERBATIM from the exact Verilator invocation
# supplied for the BASE build configuration (see sim/MANIFEST.md section 2).
# It is NOT re-derived or re-ordered from the RTL dependency graph -- it is
# preserved exactly as specified/tested to avoid introducing an untested
# command line. NOTE: Verilator resolves module instances by name via its
# own internal module graph, not by file listing order, so this order is
# not functionally load-bearing for Verilator itself; it is preserved here
# for traceability/reproducibility of the exact command that was defined.
#
# NOT included here (textual `include files, pulled into tb_tensor_core_tile.sv
# via `include, resolved through -I search paths, NOT independent compile
# units on the command line):
#   tb/tct_scoreboard.svh        (resolved via -Itb)
#   tb/tct_stimulus.svh          (resolved via -Itb)
#   assertions/tct_sva_bind.svh  (resolved via -Iassertions, guarded by +define+TCT_SVA_BIND)
#   coverage/tct_coverage.svh    (resolved via -Icoverage, guarded by +define+TCT_COVERAGE)
# =============================================================================

tb/tb_tensor_core_tile.sv
rtl/tensor_core_tile.v
rtl/ctrl_fsm.v
rtl/weight_buffer.v
rtl/act_fifo.v
rtl/pe_array.v
rtl/pe.v
rtl/requant_unit.v
