// =============================================================================
// tensor_core_tile.v
//
// Top-level INT8 output-stationary GEMM accelerator tile. Pure structural
// wiring of previously generated submodules (ctrl_fsm, weight_buffer,
// act_fifo, pe_array, requant_unit) plus the external valid/ready streaming
// handshakes and the sticky overflow status register.
//
// Requirement traceability (owned by Interface/Protocol agent):
//   REQ-GEMM-012 : weight-load external handshake (w_load_valid/ready) wired
//                  straight through from ctrl_fsm, which gates acceptance to
//                  the LOAD_WEIGHTS phase.
//   REQ-GEMM-013 : activation-input external handshake; a_in_ready is only
//                  asserted while compute is active and the activation FIFO
//                  has room (no accept without room -> no silent drop).
//   REQ-GEMM-014 : result-output external handshake; y_out_valid/last driven
//                  by ctrl_fsm's DRAIN phase, y_out_ready consumed by it.
//   REQ-GEMM-015 : backpressure -- a_in_ready deasserts on a_fifo full,
//                  w_load_ready deasserts once the load beat count is
//                  reached, y_out_valid/last only asserted with real data;
//                  no channel accepts/produces beats it cannot hold.
//   REQ-PROT-001 : valid stability -- all three external valid signals
//                  (w_load handshake driven externally by the requester,
//                  a_in_valid likewise, y_out_valid) are held by their
//                  respective sources until the paired ready is seen; this
//                  module does not drop y_out_valid/last except on the
//                  registered phase transition after a completed beat.
//   REQ-PROT-002 : ready freedom -- ready signals (w_load_ready, a_in_ready,
//                  y_out_ready consumption) are purely combinational
//                  functions of internal state and are free to deassert
//                  without waiting on valid.
//   REQ-PROT-003 : last markers -- w_load_last is a pass-through observed
//                  input (informational per ctrl_fsm), a_in_last is stored
//                  alongside data in act_fifo, y_out_last is generated by
//                  ctrl_fsm exactly on the final drain row beat.
//   REQ-TIME-001 : all internal state (FSM, buffers, accumulators, overflow)
//                  updates synchronously to `clk`/`rst_n`; no combinational
//                  loops or asynchronous set/reset anywhere in this file.
//   REQ-GEMM-018 : top-level integration wiring of all submodules per the
//                  dataflow contract (load -> compute -> drain).
//   REQ-GEMM-019 : file parses/elaborates cleanly (see verification note in
//                  the accompanying report).
//   REQ-GEMM-005/006 : N parallel requant_unit lanes instantiated for the
//                  currently draining row, producing y_out_data.
//   ERR-002      : per-lane saturation (`sat`) observed and OR-reduced.
//   U-007        : sticky `overflow` status register, cleared by reset and
//                  by a `start` pulse that begins a new op (start && !busy,
//                  i.e. FSM idle -- Risk-2: a late/spurious start mid-op must
//                  not clear a real overflow), set on any requant lane
//                  saturation while a real output beat is presented.
//   ERR-005/Risk-1: `a_fifo_flush` from ctrl_fsm (asserted in IDLE and
//                  LOAD_WEIGHTS) is wired to act_fifo's `flush` input so the
//                  activation FIFO is held empty outside COMPUTE, preventing
//                  residual over-supplied activation beats from a prior tile
//                  op from leaking into the next COMPUTE.
//
// Reset: synchronous, active-low (rst_n), matching every submodule and the
// single sequential block owned directly by this file (the overflow
// register).
// =============================================================================

module tensor_core_tile #(
    parameter integer N          = 8,
    parameter integer ACC_W      = 32,
    parameter integer DW_OUT     = 8,
    parameter integer SCALE_W    = 16,
    parameter integer SHIFT_W    = 5,
    parameter integer AFIFO_DEPTH = 16
) (
    input                     clk,
    input                     rst_n,        // synchronous active-low

    // control/status
    input                     start,        // single-cycle pulse
    input  [1:0]              cfg_mode,     // RESERVED/ignored (tied off below)
    output                    busy,
    output                    done,
    output                    overflow,     // sticky, set on any requant lane saturation

    // weight load stream
    input                     w_load_valid,
    output                    w_load_ready,
    input  [7:0]              w_load_data,
    input                     w_load_last,

    // activation input stream
    input                     a_in_valid,
    output                    a_in_ready,
    input  [N*8-1:0]          a_in_data,
    input                     a_in_last,

    // result output stream
    output                    y_out_valid,
    input                     y_out_ready,
    output [N*DW_OUT-1:0]     y_out_data,
    output                    y_out_last,

    // requant config
    input  [SCALE_W-1:0]      req_scale,
    input  [SHIFT_W-1:0]      req_shift
);

    // -------------------------------------------------------------------
    // Local width parameters mirroring the submodules' internal $clog2
    // derivations (guarded for the degenerate N==1 case).
    // -------------------------------------------------------------------
    localparam integer ADDR_W = (N*N > 1) ? $clog2(N*N) : 1;
    localparam integer ROW_W  = (N   > 1) ? $clog2(N)   : 1;
    localparam integer AFIFO_W = N*8 + 1; // {a_in_last, a_in_data}

    // -------------------------------------------------------------------
    // cfg_mode is reserved/ignored per the architecture contract; kept as
    // a port for spec compliance and referenced here in a lint-safe way so
    // no tool flags it as a dangling/unused input.
    // -------------------------------------------------------------------
    wire cfg_mode_unused = |cfg_mode;

    // -------------------------------------------------------------------
    // ctrl_fsm <-> weight_buffer wiring
    // -------------------------------------------------------------------
    wire                    wbuf_wr_en;
    wire [ADDR_W-1:0]       wbuf_wr_addr;
    // wbuf_loaded is produced by ctrl_fsm but has no external top-level port
    // to drive (not in the fixed port list); observed here only to keep the
    // submodule instantiation complete. Tied off lint-safe.
    /* verilator lint_off UNUSEDSIGNAL */
    wire                    wbuf_loaded;
    /* verilator lint_on UNUSEDSIGNAL */

    wire [N*8-1:0]          wbuf_rd_row_data;
    wire [ROW_W-1:0]        wbuf_rd_row;

    // -------------------------------------------------------------------
    // ctrl_fsm <-> act_fifo wiring
    // -------------------------------------------------------------------
    wire                    a_fifo_empty;
    wire                    a_fifo_full;
    wire                    a_fifo_rd_en;
    // Bit [AFIFO_W-1] (stored a_in_last) is intentionally not consumed here:
    // K is fixed at N by the FSM's own beat counting, so the stored last
    // marker is informational only per the dataflow contract.
    /* verilator lint_off UNUSEDSIGNAL */
    wire [AFIFO_W-1:0]      a_fifo_rd_data;
    /* verilator lint_on UNUSEDSIGNAL */
    wire                    a_fifo_wr_en;
    wire [AFIFO_W-1:0]      a_fifo_wr_data;

    // -------------------------------------------------------------------
    // ctrl_fsm <-> pe_array wiring
    // -------------------------------------------------------------------
    wire                    acc_en;
    wire                    acc_clr;
    wire [N*N*ACC_W-1:0]    acc_flat;

    // -------------------------------------------------------------------
    // ctrl_fsm phase/status signals
    // -------------------------------------------------------------------
    wire                    compute_active;
    // load_active is produced by ctrl_fsm but not consumed elsewhere in this
    // top level (no external port reflects it); observed only to keep the
    // instantiation complete.
    /* verilator lint_off UNUSEDSIGNAL */
    wire                    load_active;
    /* verilator lint_on UNUSEDSIGNAL */
    wire                    drain_active;
    wire [ROW_W-1:0]        drain_row;

    // a_fifo_flush: asserted by ctrl_fsm throughout IDLE and LOAD_WEIGHTS to
    // keep the activation FIFO held empty until COMPUTE begins (ERR-005 /
    // Risk-1: prevents residual over-supplied activation beats from a prior
    // tile op leaking into the next COMPUTE).
    wire                    a_fifo_flush;

    // =====================================================================
    // Weight load external handshake (REQ-GEMM-012)
    // =====================================================================
    ctrl_fsm #(
        .N(N)
    ) u_ctrl_fsm (
        .clk            (clk),
        .rst_n          (rst_n),

        .start          (start),

        .w_load_valid   (w_load_valid),
        .w_load_ready   (w_load_ready),
        .w_load_last    (w_load_last),
        .wbuf_wr_en     (wbuf_wr_en),
        .wbuf_wr_addr   (wbuf_wr_addr),
        .wbuf_loaded    (wbuf_loaded),

        .a_fifo_empty   (a_fifo_empty),
        .a_fifo_rd_en   (a_fifo_rd_en),
        .acc_en         (acc_en),
        .acc_clr        (acc_clr),
        .wbuf_rd_row    (wbuf_rd_row),
        .compute_active (compute_active),
        .load_active    (load_active),
        .a_fifo_flush   (a_fifo_flush),

        .drain_active   (drain_active),
        .drain_row      (drain_row),
        .y_out_ready    (y_out_ready),
        .y_out_valid    (y_out_valid),
        .y_out_last     (y_out_last),

        .busy           (busy),
        .done           (done)
    );

    // =====================================================================
    // Weight storage (REQ-GEMM-012 write side, REQ-GEMM-002 read side)
    // =====================================================================
    weight_buffer #(
        .N(N)
    ) u_weight_buffer (
        .clk         (clk),
        .rst_n       (rst_n),
        .wr_en       (wbuf_wr_en),
        .wr_addr     (wbuf_wr_addr),
        .wr_data     (w_load_data),
        .rd_row      (wbuf_rd_row),
        .rd_row_data (wbuf_rd_row_data)
    );

    // =====================================================================
    // Activation input external handshake (REQ-GEMM-013, REQ-GEMM-015)
    // a_in_ready only asserted while compute is active AND the activation
    // FIFO has room -- no beat is ever accepted that cannot be stored.
    // =====================================================================
    assign a_in_ready     = compute_active && !a_fifo_full;
    assign a_fifo_wr_en   = a_in_valid && a_in_ready;
    assign a_fifo_wr_data = {a_in_last, a_in_data};

    act_fifo #(
        .W     (AFIFO_W),
        .DEPTH (AFIFO_DEPTH)
    ) u_act_fifo (
        .clk    (clk),
        .rst_n  (rst_n),
        .wr_en  (a_fifo_wr_en),
        .wr_data(a_fifo_wr_data),
        .rd_en  (a_fifo_rd_en),
        .rd_data(a_fifo_rd_data),
        .full   (a_fifo_full),
        .empty  (a_fifo_empty),
        .flush  (a_fifo_flush)
    );

    // =====================================================================
    // PE array feed during COMPUTE (REQ-GEMM-001/002)
    //   a_vec = popped activation word (drop the stored last bit)
    //   w_row = weight row selected by ctrl_fsm.wbuf_rd_row
    // =====================================================================
    wire [N*8-1:0] pe_a_vec = a_fifo_rd_data[N*8-1:0];

    pe_array #(
        .N     (N),
        .ACC_W (ACC_W)
    ) u_pe_array (
        .clk      (clk),
        .rst_n    (rst_n),
        .a_vec    (pe_a_vec),
        .w_row    (wbuf_rd_row_data),
        .acc_en   (acc_en),
        .acc_clr  (acc_clr),
        .acc_flat (acc_flat)
    );

    // =====================================================================
    // Drain / requantize output (REQ-GEMM-014, REQ-GEMM-005/006)
    // N parallel combinational requant_unit lanes, one per output column j
    // of the currently draining row (drain_row indexes the accumulator
    // array via a variable-base indexed part-select).
    // =====================================================================
    wire [N-1:0] lane_sat;

    genvar j;
    generate
        for (j = 0; j < N; j = j + 1) begin : REQUANT_LANE
            wire signed [ACC_W-1:0] lane_acc =
                acc_flat[(drain_row*N + j)*ACC_W +: ACC_W];

            requant_unit #(
                .ACC_W   (ACC_W),
                .SCALE_W (SCALE_W),
                .SHIFT_W (SHIFT_W),
                .DW_OUT  (DW_OUT)
            ) u_requant_unit (
                .acc_in (lane_acc),
                .scale  (req_scale),
                .shift  (req_shift),
                .q_out  (y_out_data[j*DW_OUT +: DW_OUT]),
                .sat    (lane_sat[j])
            );
        end
    endgenerate

    // =====================================================================
    // Sticky overflow status (U-007, ERR-002)
    // Set when any lane of the currently draining, valid output beat
    // saturates; cleared synchronously by reset and by a `start` pulse that
    // actually begins a new op (i.e. only while the FSM is idle -- Risk-2:
    // a spurious/late start pulse arriving mid-operation, while busy is
    // high, must not wipe a real, already-latched overflow flag).
    // =====================================================================
    wire any_lane_sat = |lane_sat;

    reg overflow_r;

    always @(posedge clk) begin
        if (!rst_n) begin
            overflow_r <= 1'b0;
        end else if (start && !busy) begin
            overflow_r <= 1'b0;
        end else if (drain_active && y_out_valid && any_lane_sat) begin
            overflow_r <= 1'b1;
        end
    end

    assign overflow = overflow_r;

endmodule
