// asu_silu.sv — ASU fixed-point SiLU() lookup for the SwiGLU FFN gate.
// Implements contract C-SILU (golden/apex_golden/transformer.py): a 256-entry
// LUT + linear interpolation, bit-exact mirror of the golden arbiter
// apex_golden.transformer.silu_fx (verified exhaustively over the full 16-bit
// input domain by verif/asu/silu/tb_asu_silu.sv).
//
// SiLU(x) = x * sigmoid(x). Mirrors the canonical rtl/asu/asu_exp_lut.sv LUT
// pattern; the one structural difference is that the SiLU LUT slope is SIGNED
// (SiLU is non-monotone on the negative side), so the interpolation product is
// signed and the fractional shift is an ARITHMETIC (>>>) shift — matching the
// golden's numpy int64 floor-shift on negative products.
//
// Function:
//   in  : x_q, signed Q5.10 (SILU_IN_FRAC = 10). Contract domain is
//         [-8.0, +8.0] = [-8192, +8192]. Inputs BELOW -8192 clamp to the floor
//         entry; inputs ABOVE +8192 clamp to the ceil (idx=255, frac=64 ->
//         SiLU(8) ~= 7.997). Both clamps are part of this module's contract
//         (the FFN generator asserts gate activations are in-domain, so the
//         clamp is not exercised in a budgeted case, but it is defined here).
//   off  = x + 8192                           (15 bits, 0..16384)
//   idx  = min(off >> 6, 255)                 (top SILU_LUT_BITS = 8 bits)
//   frac = off - (idx << 6)                   (0..64; 64 only at off = 16384)
//   y    = BASE[idx] + ($signed(SLOPE[idx]) * frac) >>> 6   // SIGNED arith
//                                                           // interp shift
//   out : y_q, SIGNED Q4.12, value = y/2^12. Golden range over the whole
//         16-bit input domain is [-1140, +32757] (fits signed 16b exactly):
//         min at x ~= -1.278 (SiLU ~= -0.2785), max at the +8 clamp.
//         Invariants: silu_fx(0) == 0 exactly; silu_fx(8192) ==
//         BASE[255] + SLOPE[255].
//
// Timing: purely COMBINATIONAL (0-cycle), mirroring asu_exp_lut. The
// integrating SwiGLU datapath registers around it (ARCHITECTURE.md §0:
// area/timing are secondary to architectural correctness at signoff scope).
//
// Tables: silu_lut_tables.svh is GENERATED by golden/gen_silu_lut_tables.py
// from apex_golden.transformer._silu_lut_tables (imported, never retyped). The
// silu TB Makefile's `tables-check` target regenerates and diffs it as a build
// gate.

module asu_silu (
  input  logic signed [15:0] x_q,   // Q5.10, clamped into [-8192, +8192]
  output logic signed [15:0] y_q    // signed Q4.12, SiLU(x) * 2^12
);

  // C-SILU contract constants (NOT in the FROZEN apex_pkg; SiLU is a golden
  // model constant set): SILU_LUT_BITS = 8 (256 entries), SILU_IN_FRAC = 10
  // (input Q5.10), SILU_OUT_FRAC = 12 (output signed Q4.12), SILU_DOMAIN = 8.0.
  localparam int unsigned SILU_LUT_BITS = 8;
  localparam int unsigned SILU_IN_FRAC  = 10;
  // 16 = real-unit domain span (2*8); 4 + SILU_IN_FRAC - SILU_LUT_BITS = 6
  // bits of interpolation fraction per segment (mirrors silu_fx's FRAC_REM).
  localparam int unsigned        FRAC_REM = 4 + SILU_IN_FRAC - SILU_LUT_BITS; // 6
  // clamp limit = SILU_DOMAIN(8.0) * 2^SILU_IN_FRAC = 8192 (signed).
  localparam logic signed [15:0] LIM      = 16'sd8192;

  // Tables: canonical form is the GENERATED localparam-array include (matches
  // rtl/asu/asu_exp_lut.sv and the synthesis path). Icarus Verilog 13.0 does
  // not support unpacked-array parameters, so under __ICARUS__ the SAME golden
  // tables are loaded as a $readmemh ROM (base/slope hex emitted from the same
  // golden arbiter by verif/asu/silu/gen_silu_vectors.py). Both are the golden
  // _silu_lut_tables() values — never retyped.
`ifdef __ICARUS__
  logic signed [15:0] SILU_LUT_BASE  [0:255];
  logic signed [ 9:0] SILU_LUT_SLOPE [0:255];
  initial begin
    $readmemh("build/silu_lut_base.hex",  SILU_LUT_BASE);
    $readmemh("build/silu_lut_slope.hex", SILU_LUT_SLOPE);
  end
`else
  `include "silu_lut_tables.svh"
`endif

  logic signed [15:0] x_cl;
  logic        [14:0] off;
  logic        [ 7:0] idx;
  logic        [ 6:0] frac;
  logic signed [17:0] prod;

  always_comb begin
    // domain clamp (both directions, documented above)
    if (x_q > LIM)        x_cl = LIM;
    else if (x_q < -LIM)  x_cl = -LIM;
    else                  x_cl = x_q;

    off = 15'(unsigned'(x_cl + LIM));   // 0..16384

    // off[14] set only at off == 16384 (the min(...,255) clamp of silu_fx)
    idx  = off[14] ? 8'hFF        : off[13:6];
    frac = off[14] ? 7'd64        : {1'b0, off[5:0]};

    // signed slope * (non-negative) frac, exact in 18b; ARITHMETIC shift
    // (floor) mirrors the golden's numpy int64 >> on negative products.
    // (prod >>> FRAC_REM) is in [-26, +282]; base + it is the golden range
    // [-1140, +32757] which fits signed 16b exactly (proven in
    // gen_silu_vectors.py), so the 16b sum never overflows.
    prod = $signed(18'(SILU_LUT_SLOPE[idx])) * $signed({11'b0, frac});
    y_q  = SILU_LUT_BASE[idx] + 16'(prod >>> FRAC_REM);
  end

endmodule
