// asu_exp_lut.sv — ASU fixed-point exp() lookup.
// Implements ARCHITECTURE.md §6 / D-014 (256-entry LUT + linear interpolation)
// and apex_pkg ASU_LUT_BITS / ASU_IN_FRAC / ASU_OUT_FRAC. Bit-exact mirror of
// the golden arbiter apex_golden.compute.exp_fx (verified exhaustively over
// the full 16-bit input domain by verif/asu/smoke/tb_asu_exp_lut.sv).
//
// Function:
//   in  : z_q, signed Q6.10 (ASU_IN_FRAC = 10). Contract domain is
//         [-16.0, 0.0] = [-16384, 0]. Inputs BELOW -16384 clamp to the floor
//         entry (off = 0 -> BASE[0] = 0); inputs ABOVE 0 clamp to 0
//         (exp_q = 32768). Both clamps are part of this module's contract.
//   off  = z + 16384                          (15 bits, 0..16384)
//   idx  = min(off >> 6, 255)                 (top ASU_LUT_BITS = 8 bits)
//   frac = off - (idx << 6)                   (0..64; 64 only at off = 16384)
//   y    = BASE[idx] + ((SLOPE[idx] * frac) >> 6)   // TRUNCATING interp (C-2:
//                                                   // truncation only inside
//                                                   // LUT interpolation)
//   out : exp_q, UNSIGNED Q1.15, range 0..32768. 32768 (0x8000) encodes
//         exactly 1.0 and is produced only for z_q >= 0.
//
// Timing: purely COMBINATIONAL (0-cycle). The integrating block
// (asu_softmax) registers around it; a standalone pipeline stage was not
// needed at simulation-signoff scope (ARCHITECTURE.md §0: area/timing are
// secondary to architectural correctness).
//
// Tables: asu_exp_lut_tables.svh is GENERATED by gen_exp_lut_tables.py from
// apex_golden.compute._lut_tables (imported, never retyped). The smoke
// Makefile's `tables-check` target regenerates and diffs it as a build gate.

module asu_exp_lut
  import apex_pkg::*;
(
  input  logic signed [15:0] z_q,    // Q6.10, clamped into [-16384, 0]
  output logic        [15:0] exp_q   // UQ1.15, 0..32768 (32768 = 1.0)
);

  // 16 = 2^4 real-unit domain span; 4 + ASU_IN_FRAC - ASU_LUT_BITS = 6 bits
  // of interpolation fraction per segment (mirrors exp_fx's frac_rem).
  localparam int unsigned FRAC_REM = 4 + ASU_IN_FRAC - ASU_LUT_BITS;  // 6

  `include "asu_exp_lut_tables.svh"

  logic signed [15:0] z_cl;
  logic        [14:0] off;
  logic        [ 7:0] idx;
  logic        [ 6:0] frac;
  logic        [17:0] prod;

  always_comb begin
    // domain clamp (both directions, documented above)
    if (z_q > 16'sd0)            z_cl = 16'sd0;
    else if (z_q < -16'sd16384)  z_cl = -16'sd16384;
    else                         z_cl = z_q;

    off = 15'(unsigned'(z_cl + 16'sd16384));       // 0..16384

    // off[14] set only at off == 16384 (the min(...,255) clamp of exp_fx)
    idx  = off[14] ? 8'hFF   : off[13:6];
    frac = off[14] ? 7'd64   : {1'b0, off[5:0]};

    prod  = 18'(EXP_LUT_SLOPE[idx]) * 18'(frac);   // 11u x 7u, exact in 18b
    exp_q = 16'({1'b0, EXP_LUT_BASE[idx]}) + 16'(prod >> FRAC_REM);
  end

endmodule
