#!/usr/bin/env python3
"""gen_wide_rms_vectors.py — wide-D RMSNorm verification vectors (C-RMSW).

Oracle: golden/apex_golden/attention.py rmsnorm_fx_wide — THE arbiter for the
wide elaboration (docs/design/WIDE_RMSNORM.md §2; never edited to match RTL).
Every D <= 128 pow-2 row is additionally asserted equal to the smoke suite's
oracle rmsnorm_fx (verif/asu/smoke/gen_asu_vectors.py) — the regression link
the contract demands (wide RTL must be bit-identical on the frozen envelope).

Outputs (in --outdir), record format identical to verif/asu/sb
(tb_asu_rmsnorm_wide.sv parses the same N/B/O/Z + D/G/Y/Q records):
  vectors_wide_directed.txt  RMS_D_MAX=3584 build: D=3584 rows (random,
                             extremes, engineered RNE ties, engineered
                             μ-divisor-boundary), D ∈ {256,384,512,1024,1152},
                             D ∈ {1,64,128} regression rows, rejects
                             (B 129 / B 200 / B 3520, O 3585 / O 3648)
  vectors_wide_random.txt    ~60 seeded random rows over legal wide + narrow
                             lengths, interleaved rejects
  vectors_wide_reset.txt     phase-targeted mid-op resets (Z) on wide rows
  vectors_wide8k.txt         RMS_D_MAX=8192 build: the all-(−128) D=8192
                             corner (sum2 == 2^27 EXACTLY — the SUM_W mutant
                             detector; (r,nrm) asserted == the D=128 corner,
                             golden plumbing7b B-6), a random D=8192 row, a
                             D=3584 row, O 8193
N flags: b0 tie_odd, b1 tie_even, b2 x_extreme, b3 all_zero_x,
         b4 g_zero_lane, b5 g_extreme, b6 mu_boundary

Mutant-detection engineering (asserted here, exercised by
mutation_check_wide.py):
  * RNE ties (b0/b1): lanes with x·g·r == 2^17 (mod 2^18) at odd/even floor
    quotient — kills RNE→half-up (M3 reuse) on the shared emission line.
  * μ boundary (b6): sum2 engineered so (sum2·MU)>>(S+16) = m²−2 while
    (sum2·(MU+1))>>(S+16) = m²−1 — den (= dbg_norm) flips m−1 → m under a
    MU off-by-one, so the mutant CANNOT survive the dbg_norm compare.
"""
from __future__ import annotations

import argparse
import importlib.util as ilu
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "golden"))
import numpy as np  # noqa: E402

from apex_golden.attention import _wide_mu, rmsnorm_fx, rmsnorm_fx_wide  # noqa: E402

CHUNK = 128


def _load_smoke_oracle():
    spec = ilu.spec_from_file_location(
        "impl_gen", Path(__file__).parent.parent / "smoke/gen_asu_vectors.py")
    impl = ilu.module_from_spec(spec)
    spec.loader.exec_module(impl)
    return impl


SMOKE = _load_smoke_oracle()


def legal(d: int, dmax: int) -> bool:
    return (d <= 128 and (d & (d - 1)) == 0) or (d % CHUNK == 0 and d <= dmax)


def hx(v: int, width_bits: int) -> str:
    return f"{int(v) & ((1 << width_bits) - 1):0{width_bits // 4}x}"


class WideWriter:
    def __init__(self, dmax: int) -> None:
        self.dmax = dmax
        self.lines: list[str] = []
        self.rows = 0
        self.rejects = 0
        self.narrow_xchecked = 0

    def row(self, x: list[int], g: list[int], flags_extra: int = 0) -> None:
        d = len(x)
        assert legal(d, self.dmax), f"illegal row length {d}"
        y, r, nrm = rmsnorm_fx_wide(x, g)
        if d <= 128:
            # regression link: wide oracle == the smoke suite's oracle
            assert (y, r, nrm) == SMOKE.rmsnorm_fx(x, g), \
                f"wide oracle != smoke oracle at D={d}"
            assert (y, r, nrm) == rmsnorm_fx(x, g)
            self.narrow_xchecked += 1
        fl = flags_extra
        if any(v in (-128, 127) for v in x):
            fl |= 4
        if all(v == 0 for v in x):
            fl |= 8
        if any(v == 0 for v in g) and any(v != 0 for v in x):
            fl |= 16
        if any(v in (-32768, 32767) for v in g):
            fl |= 32
        self.lines.append(f"N {d} {fl}")
        self.lines += [f"D {hx(v, 8)}" for v in x]
        self.lines += [f"G {hx(v, 16)}" for v in g]
        self.lines += [f"Y {hx(v, 16)}" for v in y]
        self.lines.append(f"Q {r} {nrm}")
        self.rows += 1

    def bad_len(self, d: int) -> None:
        assert d <= self.dmax and not legal(d, self.dmax)
        self.lines.append(f"B {d}")
        self.rejects += 1

    def oversize(self, d: int) -> None:
        assert d > self.dmax
        self.lines.append(f"O {d}")
        self.rejects += 1

    def reset(self, d: int, phase: int, abort: int) -> None:
        self.lines.append(f"Z {d} {phase} {abort}")

    def save(self, path: Path) -> None:
        path.write_text("# generated by gen_wide_rms_vectors.py "
                        "(oracle: golden rmsnorm_fx_wide)\n"
                        + "\n".join(self.lines) + "\n")


# ── RNE tie engineering (sb house recipe, on the wide broadcast r) ───────────

def find_tie_gamma(x: list[int], r: int, want_odd: bool,
                   skip: set[int]) -> tuple[int, int] | None:
    for j in range(len(x)):
        if j in skip or x[j] == 0:
            continue
        for g in range(-32768, 32768):
            q = x[j] * g * r
            if (q & (2**18 - 1)) == 2**17 and ((q >> 18) & 1) == int(want_odd):
                return j, g
    return None


# ── μ-divisor-boundary row engineering (the MU off-by-one detector) ──────────

def mu_boundary_sum2(d: int) -> tuple[int, int]:
    """Find sum2 with (sum2·MU)>>(S+16) = m²−2 and (sum2·(MU+1))>>(S+16) =
    m²−1, so den = isqrt(mean2+1) flips m−1 → m under MU+1."""
    mu, s = _wide_mu(d)
    sh = s + 16
    smax = d * 16384
    for m in range(2, 129):
        f = m * m - 2
        lo = -(-(f << sh) // mu)                    # ceil
        hi = min(((f + 1) << sh) // mu, smax)
        if ((f + 1) << sh) % mu == 0:
            hi -= 1                                 # keep (S·mu)>>sh == f
        for s2 in range(hi, lo - 1, -1):            # top-down: boundary first
            if (s2 * mu) >> sh == f and (s2 * (mu + 1)) >> sh == f + 1:
                return s2, m
    raise AssertionError("no μ-boundary sum2 found")


def x_for_sum2(s2: int, d: int) -> list[int]:
    """Greedy squares decomposition: x (len d) with sum(x²) == s2 exactly."""
    x: list[int] = []
    rem = s2
    while rem >= 16129 and len(x) < d - 40:
        x.append(127)
        rem -= 16129
    while rem > 0:
        v = min(127, math.isqrt(rem))
        x.append(v)
        rem -= v * v
        assert len(x) <= d, "sum2 not representable in d lanes"
    x += [0] * (d - len(x))
    assert len(x) == d and sum(v * v for v in x) == s2
    return x


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="build")
    args = ap.parse_args()
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(0x3584_2026)

    D = 3584

    def rnd_x(d: int, style: float) -> list[int]:
        if style < 0.70:
            return [int(v) for v in rng.integers(-128, 128, size=d)]
        if style < 0.85:
            return [int(v) for v in rng.integers(-4, 5, size=d)]
        return [int(rng.choice([-128, 127])) if rng.random() < 0.5
                else int(rng.integers(-128, 128)) for _ in range(d)]

    def rnd_g(d: int) -> list[int]:
        return [int(v) for v in rng.integers(-32768, 32768, size=d)]

    # ═════════════════ directed (RMS_D_MAX = 3584 build) ═══════════════════
    w = WideWriter(D)
    # D=3584 random rows (contract §4), one per style
    for style in (0.1, 0.8, 0.95):
        w.row(rnd_x(D, style), rnd_g(D))
    w.row([0] * D, rnd_g(D))                       # all-zero x -> r = 8192
    xg = [0] * D
    xg[1234] = -128
    gg = [0] * D
    gg[1234] = -32768
    w.row(xg, gg)                                  # lone extreme product
    # engineered RNE ties on the wide broadcast r (M3-reuse detector)
    x_t = rnd_x(D, 0.1)
    x_t[0], x_t[1] = -128, 127
    _, r_t, _ = rmsnorm_fx_wide(x_t, [0] * D)
    t_odd = find_tie_gamma(x_t, r_t, True, {0, 1})
    t_even = find_tie_gamma(x_t, r_t, False,
                            {0, 1} | ({t_odd[0]} if t_odd else set()))
    assert t_odd and t_even, "no RNE tie lanes found at D=3584"
    g_t = rnd_g(D)
    g_t[t_odd[0]], g_t[t_even[0]] = t_odd[1], t_even[1]
    y_t, _, _ = rmsnorm_fx_wide(x_t, g_t)
    q_o = x_t[t_odd[0]] * t_odd[1] * r_t
    q_e = x_t[t_even[0]] * t_even[1] * r_t
    assert y_t[t_odd[0]] == (q_o >> 18) + 1, "odd tie must round up"
    assert y_t[t_even[0]] == (q_e >> 18), "even tie must hold"
    w.row(x_t, g_t, flags_extra=(1 | 2))
    print(f"wide ties  : lanes {t_odd[0]} (odd->up) / {t_even[0]} (even->hold)"
          f" r={r_t}")
    # engineered μ-divisor-boundary row (MU off-by-one detector)
    s2_b, m_b = mu_boundary_sum2(D)
    mu, s = _wide_mu(D)
    assert math.isqrt(((s2_b * mu) >> (s + 16)) + 1) == m_b - 1
    assert math.isqrt(((s2_b * (mu + 1)) >> (s + 16)) + 1) == m_b
    x_b = x_for_sum2(s2_b, D)
    w.row(x_b, rnd_g(D), flags_extra=64)
    print(f"μ boundary : sum2={s2_b} -> den {m_b - 1} (MU) vs {m_b} (MU+1) — "
          f"dbg_norm kills the off-by-one mutant")
    # other wide sizes: pow-2 (μ == 2^16 reduction) and non-pow-2 multiples
    for d in (256, 384, 512, 1024, 1152):
        w.row(rnd_x(d, 0.1), rnd_g(d))
    # frozen-envelope regression rows (asserted == smoke oracle above)
    for d in (1, 64, 128):
        w.row(rnd_x(d, 0.1), rnd_g(d))
    # rejects: non-multiple-of-128 (contract: D=129) + FLUSH/oversize paths
    w.bad_len(129)
    w.row(rnd_x(256, 0.1), rnd_g(256))             # clean row after reject
    w.bad_len(200)
    w.bad_len(3520)                                # multiple of 64, not 128
    w.oversize(3585)                               # last ON the overflow beat
    w.oversize(3648)                               # FLUSH path
    w.row(rnd_x(D, 0.1), rnd_g(D))                 # clean wide row after
    w.save(out / "vectors_wide_directed.txt")
    print(f"wide_directed: {w.rows} rows, {w.rejects} rejects, "
          f"{w.narrow_xchecked} narrow rows == smoke oracle")

    # ═════════════════ random (with deterministic sweeps first) ════════════
    wr = WideWriter(D)
    # every (MU, S) table entry k = 2..28 gets at least one row — a wrong
    # entry at ANY k must not escape the suite — and every narrow pow-2
    # keeps its regression link to the smoke oracle
    for d in (1, 2, 4, 8, 16, 32, 64, 128):
        wr.row(rnd_x(d, 0.1), rnd_g(d))
    for k in range(2, 29):
        wr.row(rnd_x(k * CHUNK, float(rng.random())), rnd_g(k * CHUNK))
    sizes = [1, 2, 4, 8, 16, 32, 64, 128] + [k * CHUNK for k in range(2, 29)]
    for i in range(25):
        d = int(sizes[int(rng.integers(0, len(sizes)))])
        wr.row(rnd_x(d, float(rng.random())), rnd_g(d))
        if i % 8 == 7:
            if rng.random() < 0.5:
                bad = int(rng.integers(129, D))
                while legal(bad, D):
                    bad += 1
                wr.bad_len(bad)
            else:
                wr.oversize(D + 1 + int(rng.integers(0, 40)))
    ks = {int(ln.split()[1]) // CHUNK for ln in wr.lines
          if ln.startswith("N ") and int(ln.split()[1]) > 128}
    assert ks >= set(range(2, 29)), f"k sweep incomplete: missing {set(range(2,29))-ks}"
    wr.save(out / "vectors_wide_random.txt")
    print(f"wide_random : {wr.rows} rows, {wr.rejects} rejects, "
          f"{wr.narrow_xchecked} narrow rows == smoke oracle, "
          f"k coverage 2..28 complete")

    # ═════════════════ phase-targeted mid-op resets ════════════════════════
    wz = WideWriter(D)
    # phases: 1=COLLECT 2=FLUSH 3=ISSUE 4=WAIT 5=EMIT 6=DRAIN (0=cycle-count)
    for phase in (1, 3, 4, 5, 6):
        for d in (384, D):
            wz.reset(d, phase, 0)
            wz.row(rnd_x(256, 0.1), rnd_g(256))    # clean row after
    wz.reset(D + 30, 2, 0)                         # FLUSH-phase reset
    wz.row(rnd_x(128, 0.1), rnd_g(128))
    for a in (5, 401, 3901):                       # random-cycle aborts
        wz.reset(D, 0, a)
        wz.row(rnd_x(384, 0.1), rnd_g(384))
    wz.save(out / "vectors_wide_reset.txt")
    print(f"wide_reset  : {wz.rows} verify rows, 11 targeted + 3 cycle resets")

    # ═════════════════ 8k corner set (RMS_D_MAX = 8192 build) ══════════════
    w8 = WideWriter(8192)
    x_c = [-128] * 8192
    g_c = [8192] * 8192
    assert sum(v * v for v in x_c) == 2**27        # EXACTLY the SUM_W corner
    y_c, r_c, nrm_c = rmsnorm_fx_wide(x_c, g_c)
    _, r_128, nrm_128 = rmsnorm_fx([-128] * 128, [8192] * 128)
    assert (r_c, nrm_c) == (r_128, nrm_128), "B-6 corner drifted"
    w8.row(x_c, g_c)
    w8.row(rnd_x(8192, 0.1), rnd_g(8192))
    w8.row(rnd_x(D, 0.1), rnd_g(D))                # 3584 legal here too
    w8.oversize(8193)
    w8.row(rnd_x(128, 0.1), rnd_g(128))
    w8.save(out / "vectors_wide8k.txt")
    print(f"wide8k      : {w8.rows} rows, {w8.rejects} rejects — all-(−128) "
          f"corner (r,nrm)=({r_c},{nrm_c}) == D=128 corner")

    print("GEN: all wide vector files written")


if __name__ == "__main__":
    main()
