// rope.sv — RoPE (rotary position encoding) fixed-point datapath for the
// Llama/Qwen decoder layer. Bit-exact mirror of the golden arbiter
// apex_golden.transformer.rope_fx (contract C-ROPE), verified over swept
// positions 0..127 and head_dim in {64,128} by verif/rope/smoke/tb_rope.sv.
//
// This module MIRRORS the canonical rtl/asu/asu_exp_lut.sv LUT + linear-
// interpolation pattern for the cos/sin generator, and adds the HF half-split
// rotation on top of it. It rotates ONE channel pair (i, i+half) per call:
//
//   in : u_q   phase code, Q0.PH_FRAC turn-fraction (PH_FRAC = 14), in
//              [0, 2^14). NO input clamp — the phase is periodic mod 2^14 and
//              the caller precomputes u_q = RNE(frac(m*theta_i / 2pi) * 2^14)
//              in float64 (the ONLY phase rounding — folded ONCE, upstream).
//        x_i  = x[i]      (fp16 bit pattern, the S-2 KV-write bus grid)
//        x_ih = x[i+half] (fp16 bit pattern)
//   out: y_i  = f16( x[i]*cos(phi)      - x[i+half]*sin(phi) )   (fp16 bits)
//        y_ih = f16( x[i+half]*cos(phi) + x[i]*sin(phi)      )   (fp16 bits)
//
// cos/sin LUT (cos_fx / sin_fx): 256-entry (CS_LUT_BITS = 8) over a FULL turn,
// linear interpolation, output SIGNED Q2.14 (CS_OUT_FRAC = 14, value = y/2^14
// in [-1, 1]) — the EXACT structure of asu_exp_lut, with a SIGNED slope so the
// interpolation product is signed and the fractional shift is ARITHMETIC (>>>)
// (floor toward -inf, matching the golden's numpy int64 >>):
//   idx  = u_q >> CS_FRAC_REM            (top CS_LUT_BITS = 8 bits, 0..255)
//   frac = u_q - (idx << CS_FRAC_REM)    (CS_FRAC_REM = 6 bits, 0..63)
//   y    = BASE[idx] + ($signed(SLOPE[idx]) * frac) >>> CS_FRAC_REM
// No idx==256 corner (unlike exp/silu): u_q < 2^14 so idx <= 255 always.
//
// Rotation multiply (C-ROPE): the golden mandates the two products and their
// sum be EXACT in float64 and narrowed to fp16 with ONE round-half-to-even
// (the KV-write fp16 bus). Because x is an fp16-grid value (<= 11 significand
// bits) and cos/sin are <= 15-bit fixed-point, every product x*(c/2^14) and
// the difference/sum are EXACT in IEEE double (<= ~28 significand bits) — no
// double rounding occurs, so carrying them in SV `real` is bit-identical to
// the golden's numpy float64, regardless of simulator. The single narrowing is
// the explicit round-half-to-even double->half in real_to_f16 below. cos/sin
// come from the integer LUT (the synthesizable core); the exact float64
// product + single RNE is the documented numeric contract (ARCHITECTURE.md C-1;
// §0 area/timing secondary to architectural correctness at signoff scope).
//
// Timing: purely COMBINATIONAL (0-cycle), mirroring asu_exp_lut / asu_silu.
//
// Tables: rope_lut_tables.svh is GENERATED by golden/gen_rope_lut_tables.py
// from apex_golden.transformer._cos_sin_lut_tables (imported, never retyped).
// The smoke Makefile's `tables-check` (and golden `lut-tables`) regenerate and
// diff it as a build gate. Icarus Verilog 13.0 does not support unpacked-array
// parameters, so under __ICARUS__ the SAME golden tables load as $readmemh
// ROMs (base/slope hex emitted from the same arbiter by gen_rope_vectors.py).

module rope (
  input  logic        [13:0] u_q,    // Q0.14 turn-fraction phase, [0, 2^14)
  input  logic        [15:0] x_i,    // fp16 bits, x[i]
  input  logic        [15:0] x_ih,   // fp16 bits, x[i+half]
  output logic        [15:0] y_i,    // fp16 bits, rotated x[i]
  output logic        [15:0] y_ih    // fp16 bits, rotated x[i+half]
);

  // ── C-ROPE contract constants (NOT in the FROZEN apex_pkg; RoPE is a golden
  // model constant set): 256-entry cos/sin LUT, phase Q0.14, output Q2.14. ────
  localparam int unsigned CS_LUT_BITS = 8;
  localparam int unsigned PH_FRAC     = 14;
  localparam int unsigned CS_OUT_FRAC = 14;
  localparam int unsigned CS_FRAC_REM = PH_FRAC - CS_LUT_BITS;   // 6

  // Tables: canonical form is the GENERATED localparam-array include (matches
  // rtl/asu/asu_exp_lut.sv and the synthesis path). Under __ICARUS__ the SAME
  // golden tables load as $readmemh ROMs (unpacked-array params unsupported).
`ifdef __ICARUS__
  logic signed [15:0] ROPE_COS_BASE  [0:255];
  logic signed [10:0] ROPE_COS_SLOPE [0:255];
  logic signed [15:0] ROPE_SIN_BASE  [0:255];
  logic signed [10:0] ROPE_SIN_SLOPE [0:255];
  initial begin
    $readmemh("build/rope_cos_base.hex",  ROPE_COS_BASE);
    $readmemh("build/rope_cos_slope.hex", ROPE_COS_SLOPE);
    $readmemh("build/rope_sin_base.hex",  ROPE_SIN_BASE);
    $readmemh("build/rope_sin_slope.hex", ROPE_SIN_SLOPE);
  end
`else
  `include "rope_lut_tables.svh"
`endif

  // ── pow2(p): exact real 2^p (p small; exact in IEEE double) ────────────────
  function automatic real pow2(input int p);
    real r;
    int  i;
    begin
      r = 1.0;
      if (p >= 0) for (i = 0; i < p;  i++) r = r * 2.0;
      else        for (i = 0; i < -p; i++) r = r / 2.0;
      return r;
    end
  endfunction

  // ── f16_to_real: fp16 bit pattern -> exact float64 value ───────────────────
  // Inputs are finite fp16-grid bus values; inf/NaN are not produced upstream
  // but are decoded defensively. Subnormals: value = m * 2^-24.
  function automatic real f16_to_real(input logic [15:0] b);
    logic       sgn;
    logic [4:0] e;
    logic [9:0] m;
    real        mag;
    begin
      sgn = b[15];
      e   = b[14:10];
      m   = b[9:0];
      if (e == 5'd0)
        mag = $itor({22'b0, m}) * pow2(-24);                 // subnormal / zero
      else if (e == 5'd31)
        mag = (m == 10'd0) ? pow2(1024) : pow2(1024);        // inf/NaN (unused)
      else
        // value = (1024 + m) * 2^(e - 15 - 10) = (1024 + m) * 2^(e - 25)
        mag = $itor({21'b0, (11'd1024 + {1'b0, m})}) * pow2(int'({27'b0, e}) - 25);
      return sgn ? -mag : mag;
    end
  endfunction

  // ── real_to_f16: exact float64 -> fp16 bits, ROUND-HALF-TO-EVEN ────────────
  // The ONE narrowing of the C-ROPE contract (matches numpy float64->float16).
  function automatic logic [15:0] real_to_f16(input real v);
    logic [63:0]        db;
    logic               ds;
    logic [10:0]        de;
    logic [51:0]        dm;
    logic signed [12:0] E;
    logic [52:0]        sig;         // 1.dm, 53 bits (value = sig * 2^(E-52))
    logic [52:0]        keep;
    logic [63:0]        rem, halfbit, sig64, mask;
    logic               roundup;
    int                 sh;
    logic [4:0]         eh;
    logic [15:0]        out;
    begin
      db = $realtobits(v);
      ds = db[63];
      de = db[62:52];
      dm = db[51:0];
      if (de == 11'd0) begin
        out = {ds, 15'd0};                             // 0 / double-subnormal
      end else if (de == 11'h7FF) begin
        out = {ds, 5'h1F, (dm == 0) ? 10'd0 : 10'h200};  // inf / qNaN (unused)
      end else begin
        E   = $signed({2'b0, de}) - 13'sd1023;
        sig = {1'b1, dm};
        if (E > 13'sd15) begin
          out = {ds, 5'h1F, 10'd0};                    // overflow -> inf
        end else if (E >= -13'sd14) begin
          // normal half: drop the low 42 bits of sig with RNE
          keep    = {42'b0, sig[52:42]};               // 11 bits in [1024,2047]
          rem     = {22'b0, sig[41:0]};
          halfbit = 64'd1 << 41;
          roundup = (rem > halfbit) || (rem == halfbit && keep[0]);
          keep    = keep + (roundup ? 53'd1 : 53'd0);
          if (keep[11]) begin                          // 2048 -> carry
            keep = 53'd1024;
            E    = E + 13'sd1;
          end
          if (E > 13'sd15) begin
            out = {ds, 5'h1F, 10'd0};                  // rounded up to inf
          end else begin
            eh  = 5'(int'(E) + 15);                    // [1, 30]
            out = {ds, eh, keep[9:0]};
          end
        end else begin
          // subnormal half (or 0): m10 = round(sig * 2^(E-28))
          sh = 28 - int'(E);                           // >= 43
          if (sh >= 64) begin
            out = {ds, 15'd0};
          end else begin
            sig64   = {11'b0, sig};
            mask    = (64'd1 << sh) - 64'd1;
            keep    = 53'(sig64 >> sh);
            rem     = sig64 & mask;
            halfbit = 64'd1 << (sh - 1);
            roundup = (rem > halfbit) || (rem == halfbit && keep[0]);
            keep    = keep + (roundup ? 53'd1 : 53'd0);
            out     = {ds, keep[14:0]};                // <=1024 maps correctly
          end
        end
      end
      return out;
    end
  endfunction

  // ── cos/sin LUT interpolation (mirrors asu_exp_lut; signed slope, >>>) ─────
  logic        [ 7:0] idx;
  logic        [ 5:0] frac6;
  logic signed [17:0] cprod, sprod;
  logic signed [16:0] c_val, s_val;
  int                 c_int, s_int;

  // ── rotation (exact float64 products, single RNE narrowing) ────────────────
  real cr, sr, xr_i, xr_ih, lo, hi;

  always_comb begin
    idx   = u_q[13:6];
    frac6 = u_q[5:0];

    cprod = ROPE_COS_SLOPE[idx] * $signed({1'b0, frac6});    // 11s * 7s -> 18s
    sprod = ROPE_SIN_SLOPE[idx] * $signed({1'b0, frac6});
    c_val = $signed({ROPE_COS_BASE[idx][15], ROPE_COS_BASE[idx]})
              + 17'(cprod >>> CS_FRAC_REM);
    s_val = $signed({ROPE_SIN_BASE[idx][15], ROPE_SIN_BASE[idx]})
              + 17'(sprod >>> CS_FRAC_REM);

    c_int = int'(c_val);
    s_int = int'(s_val);
    cr    = $itor(c_int) / pow2(CS_OUT_FRAC);                // c / 2^14, exact
    sr    = $itor(s_int) / pow2(CS_OUT_FRAC);                // s / 2^14, exact
    xr_i  = f16_to_real(x_i);
    xr_ih = f16_to_real(x_ih);

    lo    = xr_i  * cr - xr_ih * sr;                         // exact in float64
    hi    = xr_ih * cr + xr_i  * sr;

    y_i   = real_to_f16(lo);                                 // single RNE (S-2 bus)
    y_ih  = real_to_f16(hi);
  end

endmodule
